// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.

import type { Row } from '@rocicorp/zero'
import { createBuilder } from '@rocicorp/zero'
import type { CustomType } from 'drizzle-zero'
import type * as drizzleSchema from '../schema'

const activitiesTable = {
  name: 'activities',
  columns: {
    createdAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'created_at',
    },
    id: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    regionFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'region_fk',
    },
    type: {
      type: 'string',
      optional: false,
      customType: null as unknown as 'created' | 'updated' | 'deleted' | 'uploaded',
    },
    userFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'user_fk',
    },
    entityId: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'entity_id',
    },
    entityType: {
      type: 'string',
      optional: false,
      customType: null as unknown as 'block' | 'route' | 'area' | 'ascent' | 'file' | 'user',
      serverName: 'entity_type',
    },
    parentEntityId: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'parent_entity_id',
    },
    parentEntityType: {
      type: 'string',
      optional: true,
      customType: null as unknown as 'block' | 'route' | 'area' | 'ascent',
      serverName: 'parent_entity_type',
    },
    columnName: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'column_name',
    },
    metadata: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    oldValue: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'old_value',
    },
    newValue: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'new_value',
    },
    notified: {
      type: 'boolean',
      optional: true,
      customType: null as unknown as boolean,
    },
  },
  primaryKey: ['id'],
} as const
const areasTable = {
  name: 'areas',
  columns: {
    createdAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'created_at',
    },
    id: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    createdBy: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'created_by',
    },
    name: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    slug: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    regionFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'region_fk',
    },
    description: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    type: {
      type: 'string',
      optional: true,
      customType: null as unknown as 'area' | 'crag' | 'sector',
    },
    visibility: {
      type: 'string',
      optional: true,
      customType: null as unknown as 'public' | 'private',
    },
    walkingPaths: {
      type: 'json',
      optional: true,
      customType: null as unknown as string[],
      serverName: 'walking_paths',
    },
    geoPaths: {
      type: 'json',
      optional: true,
      customType: null as unknown as string[],
      serverName: 'geo_paths',
    },
    parentFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'parent_fk',
    },
  },
  primaryKey: ['id'],
} as const
const ascentsTable = {
  name: 'ascents',
  columns: {
    createdAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'created_at',
    },
    id: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    regionFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'region_fk',
    },
    createdBy: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'created_by',
    },
    dateTime: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'date_time',
    },
    humidity: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
    },
    notes: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    rating: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
    },
    temperature: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
    },
    type: {
      type: 'string',
      optional: false,
      customType: null as unknown as 'repeat' | 'flash' | 'send' | 'attempt',
    },
    gradeFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'grade_fk',
    },
    routeFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'route_fk',
    },
  },
  primaryKey: ['id'],
} as const
const blocksTable = {
  name: 'blocks',
  columns: {
    createdAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'created_at',
    },
    id: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    createdBy: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'created_by',
    },
    name: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    slug: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    regionFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'region_fk',
    },
    order: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    areaFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'area_fk',
    },
    geolocationFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'geolocation_fk',
    },
  },
  primaryKey: ['id'],
} as const
const bunnyStreamsTable = {
  name: 'bunnyStreams',
  columns: {
    id: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    regionFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'region_fk',
    },
    fileFk: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'file_fk',
    },
  },
  primaryKey: ['id'],
  serverName: 'bunny_streams',
} as const
const clientErrorLogsTable = {
  name: 'clientErrorLogs',
  columns: {
    createdAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'created_at',
    },
    id: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    createdBy: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'created_by',
    },
    error: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    navigator: {
      type: 'json',
      optional: true,
      customType: null as unknown as CustomType<typeof drizzleSchema, 'clientErrorLogs', 'navigator'>,
    },
    pathname: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
  },
  primaryKey: ['id'],
  serverName: 'client_error_logs',
} as const
const favoritesTable = {
  name: 'favorites',
  columns: {
    createdAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'created_at',
    },
    id: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    regionFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'region_fk',
    },
    authUserFk: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'auth_user_fk',
    },
    userFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'user_fk',
    },
    entityId: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'entity_id',
    },
    entityType: {
      type: 'string',
      optional: false,
      customType: null as unknown as 'block' | 'route' | 'area',
      serverName: 'entity_type',
    },
  },
  primaryKey: ['id'],
} as const
const filesTable = {
  name: 'files',
  columns: {
    id: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    regionFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'region_fk',
    },
    path: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    visibility: {
      type: 'string',
      optional: true,
      customType: null as unknown as 'public' | 'private',
    },
    areaFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'area_fk',
    },
    ascentFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'ascent_fk',
    },
    blockFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'block_fk',
    },
    bunnyStreamFk: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'bunny_stream_fk',
    },
    routeFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'route_fk',
    },
  },
  primaryKey: ['id'],
} as const
const firstAscensionistsTable = {
  name: 'firstAscensionists',
  columns: {
    id: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    regionFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'region_fk',
    },
    name: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    userFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'user_fk',
    },
  },
  primaryKey: ['id'],
  serverName: 'first_ascensionists',
} as const
const geolocationsTable = {
  name: 'geolocations',
  columns: {
    id: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    regionFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'region_fk',
    },
    lat: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    long: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    areaFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'area_fk',
    },
    blockFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'block_fk',
    },
  },
  primaryKey: ['id'],
} as const
const gradesTable = {
  name: 'grades',
  columns: {
    id: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    FB: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    V: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
  },
  primaryKey: ['id'],
} as const
const pushSubscriptionsTable = {
  name: 'pushSubscriptions',
  columns: {
    id: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    authUserFk: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'auth_user_fk',
    },
    userFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'user_fk',
    },
    endpoint: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    expirationTime: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'expiration_time',
    },
    p256dh: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    auth: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
  },
  primaryKey: ['id'],
  serverName: 'push_subscriptions',
} as const
const regionInvitationsTable = {
  name: 'regionInvitations',
  columns: {
    createdAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'created_at',
    },
    id: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    regionFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'region_fk',
    },
    token: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    invitedByFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'invited_by',
    },
    email: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    expiresAt: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'expires_at',
    },
    status: {
      type: 'string',
      optional: true,
      customType: null as unknown as 'pending' | 'accepted' | 'expired',
    },
    acceptedAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'accepted_at',
    },
    acceptedByFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'accepted_by',
    },
  },
  primaryKey: ['id'],
  serverName: 'region_invitations',
} as const
const regionMembersTable = {
  name: 'regionMembers',
  columns: {
    createdAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'created_at',
    },
    id: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    regionFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'region_fk',
    },
    role: {
      type: 'string',
      optional: false,
      customType: null as unknown as 'app_admin' | 'region_user' | 'region_maintainer' | 'region_admin',
    },
    isActive: {
      type: 'boolean',
      optional: true,
      customType: null as unknown as boolean,
      serverName: 'is_active',
    },
    authUserFk: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'auth_user_fk',
    },
    invitedByFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'invited_by',
    },
    userFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'user_fk',
    },
  },
  primaryKey: ['id'],
  serverName: 'region_members',
} as const
const regionsTable = {
  name: 'regions',
  columns: {
    createdAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'created_at',
    },
    id: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    createdBy: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'created_by',
    },
    maxMembers: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'max_members',
    },
    name: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    settings: {
      type: 'json',
      optional: true,
      customType: null as unknown as CustomType<typeof drizzleSchema, 'regions', 'settings'>,
    },
  },
  primaryKey: ['id'],
} as const
const rolePermissionsTable = {
  name: 'rolePermissions',
  columns: {
    id: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    role: {
      type: 'string',
      optional: false,
      customType: null as unknown as 'app_admin' | 'region_user' | 'region_maintainer' | 'region_admin',
    },
    permission: {
      type: 'string',
      optional: false,
      customType: null as unknown as CustomType<typeof drizzleSchema, 'rolePermissions', 'permission'>,
    },
  },
  primaryKey: ['id'],
  serverName: 'role_permissions',
} as const
const routeExternalResource27CragsTable = {
  name: 'routeExternalResource27crags',
  columns: {
    id: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    regionFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'region_fk',
    },
    name: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    searchable_id: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
    },
    searchable_type: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    country_name: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    location_name: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    description: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    crag_id: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
    },
    latitude: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
    },
    longitude: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
    },
    path: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    url: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    externalResourcesFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'external_resources_fk',
    },
  },
  primaryKey: ['id'],
  serverName: 'route_external_resource_27crags',
} as const
const routeExternalResource8ATable = {
  name: 'routeExternalResource8a',
  columns: {
    id: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    regionFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'region_fk',
    },
    zlaggableName: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'zlaggable_name',
    },
    zlaggableSlug: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'zlaggable_slug',
    },
    zlaggableId: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'zlaggable_id',
    },
    cragName: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'crag_name',
    },
    cragSlug: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'crag_slug',
    },
    countrySlug: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'country_slug',
    },
    countryName: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'country_name',
    },
    areaName: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'area_name',
    },
    areaSlug: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'area_slug',
    },
    sectorName: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'sector_name',
    },
    sectorSlug: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'sector_slug',
    },
    gradeIndex: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'grade_index',
    },
    type: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
    },
    category: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
    },
    averageRating: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'average_rating',
    },
    difficulty: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    url: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    externalResourcesFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'external_resources_fk',
    },
  },
  primaryKey: ['id'],
  serverName: 'route_external_resource_8a',
} as const
const routeExternalResourceTheCragTable = {
  name: 'routeExternalResourceTheCrag',
  columns: {
    id: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    regionFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'region_fk',
    },
    name: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    description: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    grade: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    node: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
    },
    rating: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
    },
    tags: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    url: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    externalResourcesFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'external_resources_fk',
    },
  },
  primaryKey: ['id'],
  serverName: 'route_external_resource_the_crag',
} as const
const routeExternalResourcesTable = {
  name: 'routeExternalResources',
  columns: {
    id: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    regionFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'region_fk',
    },
    routeFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'route_fk',
    },
    externalResource8aFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'external_resource_8a_fk',
    },
    externalResource27cragsFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'external_resource_27crags_fk',
    },
    externalResourceTheCragFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'external_resource_the_crag_fk',
    },
  },
  primaryKey: ['id'],
  serverName: 'route_external_resources',
} as const
const routesTable = {
  name: 'routes',
  columns: {
    createdAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'created_at',
    },
    id: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    createdBy: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'created_by',
    },
    name: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    slug: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    regionFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'region_fk',
    },
    description: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    rating: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
    },
    firstAscentYear: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'first_ascent_year',
    },
    userRating: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'user_rating',
    },
    areaFks: {
      type: 'json',
      optional: true,
      customType: null as unknown as number[],
      serverName: 'area_fks',
    },
    areaIds: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'area_ids',
    },
    blockFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'block_fk',
    },
    externalResourcesFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'external_resources_fk',
    },
    gradeFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'grade_fk',
    },
    userGradeFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'user_grade_fk',
    },
  },
  primaryKey: ['id'],
} as const
const routesToFirstAscensionistsTable = {
  name: 'routesToFirstAscensionists',
  columns: {
    id: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    regionFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'region_fk',
    },
    firstAscensionistFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'first_ascensionist_fk',
    },
    routeFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'route_fk',
    },
  },
  primaryKey: ['id'],
  serverName: 'routes_to_first_ascensionists',
} as const
const routesToTagsTable = {
  name: 'routesToTags',
  columns: {
    regionFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'region_fk',
    },
    routeFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'route_fk',
    },
    tagFk: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'tag_fk',
    },
  },
  primaryKey: ['routeFk', 'tagFk'],
  serverName: 'routes_to_tags',
} as const
const tagsTable = {
  name: 'tags',
  columns: {
    id: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
  },
  primaryKey: ['id'],
} as const
const topoRoutesTable = {
  name: 'topoRoutes',
  columns: {
    id: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    regionFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'region_fk',
    },
    topType: {
      type: 'string',
      optional: false,
      customType: null as unknown as 'top' | 'topout',
      serverName: 'top_type',
    },
    path: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    routeFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'route_fk',
    },
    topoFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'topo_fk',
    },
  },
  primaryKey: ['id'],
  serverName: 'topo_routes',
} as const
const toposTable = {
  name: 'topos',
  columns: {
    id: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    regionFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'region_fk',
    },
    blockFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'block_fk',
    },
    fileFk: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'file_fk',
    },
  },
  primaryKey: ['id'],
} as const
const userRolesTable = {
  name: 'userRoles',
  columns: {
    id: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    authUserFk: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'auth_user_fk',
    },
    role: {
      type: 'string',
      optional: false,
      customType: null as unknown as 'app_admin' | 'region_user' | 'region_maintainer' | 'region_admin',
    },
  },
  primaryKey: ['id'],
  serverName: 'user_roles',
} as const
const userSettingsTable = {
  name: 'userSettings',
  columns: {
    id: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    authUserFk: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'auth_user_fk',
    },
    userFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'user_fk',
    },
    cookie8a: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'cookie_8a',
    },
    cookie27crags: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'cookie_27crags',
    },
    cookieTheCrag: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'cookie_the_crag',
    },
    gradingScale: {
      type: 'string',
      optional: true,
      customType: null as unknown as 'FB' | 'V',
      serverName: 'grading_scale',
    },
    notifyModerations: {
      type: 'boolean',
      optional: true,
      customType: null as unknown as boolean,
      serverName: 'notify_moderations',
    },
    notifyNewAscents: {
      type: 'boolean',
      optional: true,
      customType: null as unknown as boolean,
      serverName: 'notify_new_ascents',
    },
    notifyNewUsers: {
      type: 'boolean',
      optional: true,
      customType: null as unknown as boolean,
      serverName: 'notify_new_users',
    },
  },
  primaryKey: ['id'],
  serverName: 'user_settings',
} as const
const usersTable = {
  name: 'users',
  columns: {
    createdAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'created_at',
    },
    id: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    username: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    authUserFk: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'auth_user_fk',
    },
    firstAscensionistFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'first_ascentionist_fk',
    },
    userSettingsFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'user_settings_fk',
    },
  },
  primaryKey: ['id'],
} as const
const activitiesRelationships = {
  region: [{ sourceField: ['regionFk'], destField: ['id'], destSchema: 'regions', cardinality: 'one' }],
  user: [{ sourceField: ['userFk'], destField: ['id'], destSchema: 'users', cardinality: 'one' }],
} as const
const areasRelationships = {
  author: [{ sourceField: ['createdBy'], destField: ['id'], destSchema: 'users', cardinality: 'one' }],
  parent: [{ sourceField: ['parentFk'], destField: ['id'], destSchema: 'areas', cardinality: 'one' }],
  region: [{ sourceField: ['regionFk'], destField: ['id'], destSchema: 'regions', cardinality: 'one' }],
  areas: [{ sourceField: ['id'], destField: ['parentFk'], destSchema: 'areas', cardinality: 'many' }],
  blocks: [{ sourceField: ['id'], destField: ['areaFk'], destSchema: 'blocks', cardinality: 'many' }],
  files: [{ sourceField: ['id'], destField: ['areaFk'], destSchema: 'files', cardinality: 'many' }],
  parkingLocations: [{ sourceField: ['id'], destField: ['areaFk'], destSchema: 'geolocations', cardinality: 'many' }],
} as const
const ascentsRelationships = {
  author: [{ sourceField: ['createdBy'], destField: ['id'], destSchema: 'users', cardinality: 'one' }],
  grade: [{ sourceField: ['gradeFk'], destField: ['id'], destSchema: 'grades', cardinality: 'one' }],
  region: [{ sourceField: ['regionFk'], destField: ['id'], destSchema: 'regions', cardinality: 'one' }],
  route: [{ sourceField: ['routeFk'], destField: ['id'], destSchema: 'routes', cardinality: 'one' }],
  files: [{ sourceField: ['id'], destField: ['ascentFk'], destSchema: 'files', cardinality: 'many' }],
} as const
const blocksRelationships = {
  area: [{ sourceField: ['areaFk'], destField: ['id'], destSchema: 'areas', cardinality: 'one' }],
  author: [{ sourceField: ['createdBy'], destField: ['id'], destSchema: 'users', cardinality: 'one' }],
  geolocation: [{ sourceField: ['geolocationFk'], destField: ['id'], destSchema: 'geolocations', cardinality: 'one' }],
  region: [{ sourceField: ['regionFk'], destField: ['id'], destSchema: 'regions', cardinality: 'one' }],
  files: [{ sourceField: ['id'], destField: ['blockFk'], destSchema: 'files', cardinality: 'many' }],
  routes: [{ sourceField: ['id'], destField: ['blockFk'], destSchema: 'routes', cardinality: 'many' }],
  topos: [{ sourceField: ['id'], destField: ['blockFk'], destSchema: 'topos', cardinality: 'many' }],
} as const
const bunnyStreamsRelationships = {
  file: [{ sourceField: ['fileFk'], destField: ['id'], destSchema: 'files', cardinality: 'one' }],
  region: [{ sourceField: ['regionFk'], destField: ['id'], destSchema: 'regions', cardinality: 'one' }],
} as const
const favoritesRelationships = {
  user: [{ sourceField: ['userFk'], destField: ['id'], destSchema: 'users', cardinality: 'one' }],
  authUser: [{ sourceField: ['authUserFk'], destField: ['id'], destSchema: 'users', cardinality: 'one' }],
  region: [{ sourceField: ['regionFk'], destField: ['id'], destSchema: 'regions', cardinality: 'one' }],
} as const
const filesRelationships = {
  area: [{ sourceField: ['areaFk'], destField: ['id'], destSchema: 'areas', cardinality: 'one' }],
  ascent: [{ sourceField: ['ascentFk'], destField: ['id'], destSchema: 'ascents', cardinality: 'one' }],
  block: [{ sourceField: ['blockFk'], destField: ['id'], destSchema: 'blocks', cardinality: 'one' }],
  bunnyStream: [{ sourceField: ['bunnyStreamFk'], destField: ['id'], destSchema: 'bunnyStreams', cardinality: 'one' }],
  region: [{ sourceField: ['regionFk'], destField: ['id'], destSchema: 'regions', cardinality: 'one' }],
  route: [{ sourceField: ['routeFk'], destField: ['id'], destSchema: 'routes', cardinality: 'one' }],
} as const
const firstAscensionistsRelationships = {
  region: [{ sourceField: ['regionFk'], destField: ['id'], destSchema: 'regions', cardinality: 'one' }],
  user: [{ sourceField: ['userFk'], destField: ['id'], destSchema: 'users', cardinality: 'one' }],
  routes: [
    {
      sourceField: ['id'],
      destField: ['firstAscensionistFk'],
      destSchema: 'routesToFirstAscensionists',
      cardinality: 'many',
    },
  ],
} as const
const geolocationsRelationships = {
  area: [{ sourceField: ['areaFk'], destField: ['id'], destSchema: 'areas', cardinality: 'one' }],
  block: [{ sourceField: ['blockFk'], destField: ['id'], destSchema: 'blocks', cardinality: 'one' }],
  region: [{ sourceField: ['regionFk'], destField: ['id'], destSchema: 'regions', cardinality: 'one' }],
} as const
const gradesRelationships = {
  ascents: [{ sourceField: ['id'], destField: ['gradeFk'], destSchema: 'ascents', cardinality: 'many' }],
  routes: [{ sourceField: ['id'], destField: ['gradeFk'], destSchema: 'routes', cardinality: 'many' }],
} as const
const pushSubscriptionsRelationships = {
  user: [{ sourceField: ['userFk'], destField: ['id'], destSchema: 'users', cardinality: 'one' }],
  authUser: [{ sourceField: ['authUserFk'], destField: ['id'], destSchema: 'users', cardinality: 'one' }],
} as const
const regionInvitationsRelationships = {
  region: [{ sourceField: ['regionFk'], destField: ['id'], destSchema: 'regions', cardinality: 'one' }],
  invitedBy: [{ sourceField: ['invitedByFk'], destField: ['id'], destSchema: 'users', cardinality: 'one' }],
  acceptedBy: [{ sourceField: ['acceptedByFk'], destField: ['id'], destSchema: 'users', cardinality: 'one' }],
} as const
const regionMembersRelationships = {
  user: [{ sourceField: ['userFk'], destField: ['id'], destSchema: 'users', cardinality: 'one' }],
  invitedBy: [{ sourceField: ['invitedByFk'], destField: ['id'], destSchema: 'users', cardinality: 'one' }],
  region: [{ sourceField: ['regionFk'], destField: ['id'], destSchema: 'regions', cardinality: 'one' }],
  rolePermission: [{ sourceField: ['role'], destField: ['role'], destSchema: 'rolePermissions', cardinality: 'one' }],
  authUser: [{ sourceField: ['authUserFk'], destField: ['id'], destSchema: 'users', cardinality: 'one' }],
} as const
const regionsRelationships = {
  members: [{ sourceField: ['id'], destField: ['regionFk'], destSchema: 'regionMembers', cardinality: 'many' }],
} as const
const rolePermissionsRelationships = {
  regionMembers: [{ sourceField: ['role'], destField: ['role'], destSchema: 'regionMembers', cardinality: 'many' }],
} as const
const routeExternalResource27CragsRelationships = {
  externalResources: [
    {
      sourceField: ['externalResourcesFk'],
      destField: ['id'],
      destSchema: 'routeExternalResources',
      cardinality: 'one',
    },
  ],
  region: [{ sourceField: ['regionFk'], destField: ['id'], destSchema: 'regions', cardinality: 'one' }],
} as const
const routeExternalResource8ARelationships = {
  externalResources: [
    {
      sourceField: ['externalResourcesFk'],
      destField: ['id'],
      destSchema: 'routeExternalResources',
      cardinality: 'one',
    },
  ],
  region: [{ sourceField: ['regionFk'], destField: ['id'], destSchema: 'regions', cardinality: 'one' }],
} as const
const routeExternalResourceTheCragRelationships = {
  externalResources: [
    {
      sourceField: ['externalResourcesFk'],
      destField: ['id'],
      destSchema: 'routeExternalResources',
      cardinality: 'one',
    },
  ],
  region: [{ sourceField: ['regionFk'], destField: ['id'], destSchema: 'regions', cardinality: 'one' }],
} as const
const routeExternalResourcesRelationships = {
  route: [{ sourceField: ['routeFk'], destField: ['id'], destSchema: 'routes', cardinality: 'one' }],
  region: [{ sourceField: ['regionFk'], destField: ['id'], destSchema: 'regions', cardinality: 'one' }],
  externalResource8a: [
    {
      sourceField: ['externalResource8aFk'],
      destField: ['id'],
      destSchema: 'routeExternalResource8a',
      cardinality: 'one',
    },
  ],
  externalResource27crags: [
    {
      sourceField: ['externalResource27cragsFk'],
      destField: ['id'],
      destSchema: 'routeExternalResource27crags',
      cardinality: 'one',
    },
  ],
  externalResourceTheCrag: [
    {
      sourceField: ['externalResourceTheCragFk'],
      destField: ['id'],
      destSchema: 'routeExternalResourceTheCrag',
      cardinality: 'one',
    },
  ],
} as const
const routesRelationships = {
  author: [{ sourceField: ['createdBy'], destField: ['id'], destSchema: 'users', cardinality: 'one' }],
  block: [{ sourceField: ['blockFk'], destField: ['id'], destSchema: 'blocks', cardinality: 'one' }],
  externalResources: [
    {
      sourceField: ['externalResourcesFk'],
      destField: ['id'],
      destSchema: 'routeExternalResources',
      cardinality: 'one',
    },
  ],
  grade: [{ sourceField: ['gradeFk'], destField: ['id'], destSchema: 'grades', cardinality: 'one' }],
  region: [{ sourceField: ['regionFk'], destField: ['id'], destSchema: 'regions', cardinality: 'one' }],
  firstAscents: [
    { sourceField: ['id'], destField: ['routeFk'], destSchema: 'routesToFirstAscensionists', cardinality: 'many' },
  ],
  ascents: [{ sourceField: ['id'], destField: ['routeFk'], destSchema: 'ascents', cardinality: 'many' }],
  files: [{ sourceField: ['id'], destField: ['routeFk'], destSchema: 'files', cardinality: 'many' }],
  tags: [{ sourceField: ['id'], destField: ['routeFk'], destSchema: 'routesToTags', cardinality: 'many' }],
} as const
const routesToFirstAscensionistsRelationships = {
  firstAscensionist: [
    { sourceField: ['firstAscensionistFk'], destField: ['id'], destSchema: 'firstAscensionists', cardinality: 'one' },
  ],
  region: [{ sourceField: ['regionFk'], destField: ['id'], destSchema: 'regions', cardinality: 'one' }],
  route: [{ sourceField: ['routeFk'], destField: ['id'], destSchema: 'routes', cardinality: 'one' }],
} as const
const routesToTagsRelationships = {
  region: [{ sourceField: ['regionFk'], destField: ['id'], destSchema: 'regions', cardinality: 'one' }],
  route: [{ sourceField: ['routeFk'], destField: ['id'], destSchema: 'routes', cardinality: 'one' }],
  tag: [{ sourceField: ['tagFk'], destField: ['id'], destSchema: 'tags', cardinality: 'one' }],
} as const
const tagsRelationships = {
  routes: [{ sourceField: ['id'], destField: ['tagFk'], destSchema: 'routesToTags', cardinality: 'many' }],
} as const
const topoRoutesRelationships = {
  region: [{ sourceField: ['regionFk'], destField: ['id'], destSchema: 'regions', cardinality: 'one' }],
  route: [{ sourceField: ['routeFk'], destField: ['id'], destSchema: 'routes', cardinality: 'one' }],
  topo: [{ sourceField: ['topoFk'], destField: ['id'], destSchema: 'topos', cardinality: 'one' }],
} as const
const toposRelationships = {
  block: [{ sourceField: ['blockFk'], destField: ['id'], destSchema: 'blocks', cardinality: 'one' }],
  file: [{ sourceField: ['fileFk'], destField: ['id'], destSchema: 'files', cardinality: 'one' }],
  region: [{ sourceField: ['regionFk'], destField: ['id'], destSchema: 'regions', cardinality: 'one' }],
  routes: [{ sourceField: ['id'], destField: ['topoFk'], destSchema: 'topoRoutes', cardinality: 'many' }],
} as const
const userRolesRelationships = {
  rolePermission: [{ sourceField: ['role'], destField: ['role'], destSchema: 'rolePermissions', cardinality: 'one' }],
} as const
const userSettingsRelationships = {
  user: [{ sourceField: ['userFk'], destField: ['id'], destSchema: 'users', cardinality: 'one' }],
  authUser: [{ sourceField: ['authUserFk'], destField: ['id'], destSchema: 'users', cardinality: 'one' }],
} as const
const usersRelationships = {
  authUser: [{ sourceField: ['authUserFk'], destField: ['id'], destSchema: 'users', cardinality: 'one' }],
  firstAscensionist: [
    { sourceField: ['firstAscensionistFk'], destField: ['id'], destSchema: 'firstAscensionists', cardinality: 'one' },
  ],
  userSettings: [
    { sourceField: ['userSettingsFk'], destField: ['id'], destSchema: 'userSettings', cardinality: 'one' },
  ],
  areas: [{ sourceField: ['id'], destField: ['createdBy'], destSchema: 'areas', cardinality: 'many' }],
  ascents: [{ sourceField: ['id'], destField: ['createdBy'], destSchema: 'ascents', cardinality: 'many' }],
  blocks: [{ sourceField: ['id'], destField: ['createdBy'], destSchema: 'blocks', cardinality: 'many' }],
  favorites: [{ sourceField: ['id'], destField: ['userFk'], destSchema: 'favorites', cardinality: 'many' }],
  routes: [{ sourceField: ['id'], destField: ['createdBy'], destSchema: 'routes', cardinality: 'many' }],
  pushSubscriptions: [
    { sourceField: ['id'], destField: ['userFk'], destSchema: 'pushSubscriptions', cardinality: 'many' },
  ],
  regionMemberships: [{ sourceField: ['id'], destField: ['userFk'], destSchema: 'regionMembers', cardinality: 'many' }],
} as const
/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  tables: {
    activities: activitiesTable,
    areas: areasTable,
    ascents: ascentsTable,
    blocks: blocksTable,
    bunnyStreams: bunnyStreamsTable,
    clientErrorLogs: clientErrorLogsTable,
    favorites: favoritesTable,
    files: filesTable,
    firstAscensionists: firstAscensionistsTable,
    geolocations: geolocationsTable,
    grades: gradesTable,
    pushSubscriptions: pushSubscriptionsTable,
    regionInvitations: regionInvitationsTable,
    regionMembers: regionMembersTable,
    regions: regionsTable,
    rolePermissions: rolePermissionsTable,
    routeExternalResource27crags: routeExternalResource27CragsTable,
    routeExternalResource8a: routeExternalResource8ATable,
    routeExternalResourceTheCrag: routeExternalResourceTheCragTable,
    routeExternalResources: routeExternalResourcesTable,
    routes: routesTable,
    routesToFirstAscensionists: routesToFirstAscensionistsTable,
    routesToTags: routesToTagsTable,
    tags: tagsTable,
    topoRoutes: topoRoutesTable,
    topos: toposTable,
    userRoles: userRolesTable,
    userSettings: userSettingsTable,
    users: usersTable,
  },
  relationships: {
    activities: activitiesRelationships,
    areas: areasRelationships,
    ascents: ascentsRelationships,
    blocks: blocksRelationships,
    bunnyStreams: bunnyStreamsRelationships,
    favorites: favoritesRelationships,
    files: filesRelationships,
    firstAscensionists: firstAscensionistsRelationships,
    geolocations: geolocationsRelationships,
    grades: gradesRelationships,
    pushSubscriptions: pushSubscriptionsRelationships,
    regionInvitations: regionInvitationsRelationships,
    regionMembers: regionMembersRelationships,
    regions: regionsRelationships,
    rolePermissions: rolePermissionsRelationships,
    routeExternalResource27crags: routeExternalResource27CragsRelationships,
    routeExternalResource8a: routeExternalResource8ARelationships,
    routeExternalResourceTheCrag: routeExternalResourceTheCragRelationships,
    routeExternalResources: routeExternalResourcesRelationships,
    routes: routesRelationships,
    routesToFirstAscensionists: routesToFirstAscensionistsRelationships,
    routesToTags: routesToTagsRelationships,
    tags: tagsRelationships,
    topoRoutes: topoRoutesRelationships,
    topos: toposRelationships,
    userRoles: userRolesRelationships,
    userSettings: userSettingsRelationships,
    users: usersRelationships,
  },
  enableLegacyQueries: false,
  enableLegacyMutators: false,
} as const

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema
/**
 * Represents a row from the "activities" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["activities"] instead from "@rocicorp/zero".
 */
export type Activity = Row['activities']
/**
 * Represents a row from the "areas" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["areas"] instead from "@rocicorp/zero".
 */
export type Area = Row['areas']
/**
 * Represents a row from the "ascents" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["ascents"] instead from "@rocicorp/zero".
 */
export type Ascent = Row['ascents']
/**
 * Represents a row from the "blocks" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["blocks"] instead from "@rocicorp/zero".
 */
export type Block = Row['blocks']
/**
 * Represents a row from the "bunnyStreams" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["bunnyStreams"] instead from "@rocicorp/zero".
 */
export type BunnyStream = Row['bunnyStreams']
/**
 * Represents a row from the "clientErrorLogs" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["clientErrorLogs"] instead from "@rocicorp/zero".
 */
export type ClientErrorLog = Row['clientErrorLogs']
/**
 * Represents a row from the "favorites" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["favorites"] instead from "@rocicorp/zero".
 */
export type Favorite = Row['favorites']
/**
 * Represents a row from the "files" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["files"] instead from "@rocicorp/zero".
 */
export type File = Row['files']
/**
 * Represents a row from the "firstAscensionists" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["firstAscensionists"] instead from "@rocicorp/zero".
 */
export type FirstAscensionist = Row['firstAscensionists']
/**
 * Represents a row from the "geolocations" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["geolocations"] instead from "@rocicorp/zero".
 */
export type Geolocation = Row['geolocations']
/**
 * Represents a row from the "grades" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["grades"] instead from "@rocicorp/zero".
 */
export type Grade = Row['grades']
/**
 * Represents a row from the "pushSubscriptions" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["pushSubscriptions"] instead from "@rocicorp/zero".
 */
export type PushSubscription = Row['pushSubscriptions']
/**
 * Represents a row from the "regionInvitations" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["regionInvitations"] instead from "@rocicorp/zero".
 */
export type RegionInvitation = Row['regionInvitations']
/**
 * Represents a row from the "regionMembers" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["regionMembers"] instead from "@rocicorp/zero".
 */
export type RegionMember = Row['regionMembers']
/**
 * Represents a row from the "regions" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["regions"] instead from "@rocicorp/zero".
 */
export type Region = Row['regions']
/**
 * Represents a row from the "rolePermissions" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["rolePermissions"] instead from "@rocicorp/zero".
 */
export type RolePermission = Row['rolePermissions']
/**
 * Represents a row from the "routeExternalResource27crags" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["routeExternalResource27crags"] instead from "@rocicorp/zero".
 */
export type RouteExternalResource27Crag = Row['routeExternalResource27crags']
/**
 * Represents a row from the "routeExternalResource8a" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["routeExternalResource8a"] instead from "@rocicorp/zero".
 */
export type RouteExternalResource8A = Row['routeExternalResource8a']
/**
 * Represents a row from the "routeExternalResourceTheCrag" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["routeExternalResourceTheCrag"] instead from "@rocicorp/zero".
 */
export type RouteExternalResourceTheCrag = Row['routeExternalResourceTheCrag']
/**
 * Represents a row from the "routeExternalResources" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["routeExternalResources"] instead from "@rocicorp/zero".
 */
export type RouteExternalResource = Row['routeExternalResources']
/**
 * Represents a row from the "routes" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["routes"] instead from "@rocicorp/zero".
 */
export type Route = Row['routes']
/**
 * Represents a row from the "routesToFirstAscensionists" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["routesToFirstAscensionists"] instead from "@rocicorp/zero".
 */
export type RoutesToFirstAscensionist = Row['routesToFirstAscensionists']
/**
 * Represents a row from the "routesToTags" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["routesToTags"] instead from "@rocicorp/zero".
 */
export type RoutesToTag = Row['routesToTags']
/**
 * Represents a row from the "tags" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["tags"] instead from "@rocicorp/zero".
 */
export type Tag = Row['tags']
/**
 * Represents a row from the "topoRoutes" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["topoRoutes"] instead from "@rocicorp/zero".
 */
export type TopoRoute = Row['topoRoutes']
/**
 * Represents a row from the "topos" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["topos"] instead from "@rocicorp/zero".
 */
export type Topo = Row['topos']
/**
 * Represents a row from the "userRoles" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["userRoles"] instead from "@rocicorp/zero".
 */
export type UserRole = Row['userRoles']
/**
 * Represents a row from the "userSettings" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["userSettings"] instead from "@rocicorp/zero".
 */
export type UserSetting = Row['userSettings']
/**
 * Represents a row from the "users" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["users"] instead from "@rocicorp/zero".
 */
export type User = Row['users']

/**
 * Represents the ZQL query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const zql = createBuilder(schema)
/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use `zql` instead.
 */
export const builder = zql

/** Defines the default types for Zero */
declare module '@rocicorp/zero' {
  interface DefaultTypes {
    schema: Schema
  }
}
