import type { IconProps } from '@lucide/svelte'
import {
  ArrowLeft,
  ArrowRight,
  AtSign,
  Bold,
  Box,
  Check,
  ChevronDown,
  ChevronRight,
  Expand,
  FileText,
  ImageOff,
  Italic,
  Layers,
  Link,
  List,
  ListFilter,
  LocateFixed,
  Map,
  MapPin,
  Minus,
  Mountain,
  Plus,
  Redo2,
  RefreshCw,
  Route,
  Search,
  Share2,
  Shrink,
  SquareParking,
  SquarePen,
  Star,
  Undo2,
  User,
  X,
} from '@lucide/svelte'
import type { Component } from 'svelte'

/**
 * Central registry mapping semantic, library-agnostic icon names to their
 * concrete implementations. This is the single place that knows about the
 * underlying icon library — swapping libraries only requires updating the
 * values here, every call site keeps using `<Icon name="..." />`.
 */
export const icons = {
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'at-sign': AtSign,
  area: Mountain,
  block: Box,
  bold: Bold,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  close: X,
  collapse: Shrink,
  edit: SquarePen,
  expand: Expand,
  'file-text': FileText,
  filter: ListFilter,
  'image-off': ImageOff,
  italic: Italic,
  layers: Layers,
  link: Link,
  list: List,
  locate: LocateFixed,
  map: Map,
  'map-pin': MapPin,
  minus: Minus,
  parking: SquareParking,
  plus: Plus,
  redo: Redo2,
  route: Route,
  search: Search,
  share: Share2,
  star: Star,
  sync: RefreshCw,
  undo: Undo2,
  user: User,
} satisfies Record<string, Component<IconProps>>

export type IconName = keyof typeof icons
