import type { IconProps } from '@lucide/svelte'
import {
  ArrowLeft,
  ArrowRight,
  ArrowUpDown,
  AtSign,
  Bold,
  Bookmark,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Code,
  Copy,
  Ellipsis,
  Eye,
  EyeOff,
  FileText,
  GripHorizontal,
  GripVertical,
  History,
  Image,
  ImageOff,
  Info,
  Italic,
  Layers,
  Link,
  List,
  ListFilter,
  LocateFixed,
  Lock,
  LogOut,
  Map,
  MapPin,
  MapPinSearch,
  MapPinX,
  Maximize2,
  Minimize2,
  Minus,
  Mountain,
  Navigation,
  Pause,
  Pickaxe,
  Play,
  Plus,
  Redo2,
  RefreshCw,
  Route,
  Search,
  Settings,
  Share,
  Smartphone,
  SquareParking,
  SquarePen,
  Star,
  Stone,
  TentTree,
  Trash2,
  TrendingUp,
  TriangleAlert,
  Undo2,
  User,
  Users,
  UsersRound,
  Volume1,
  VolumeX,
  WifiOff,
  X,
} from '@lucide/svelte'
import type { Component } from 'svelte'

/**
 * Central registry mapping semantic, library-agnostic icon names to their
 * concrete implementations. This is the single place that knows about the
 * underlying icon library — swapping libraries only requires updating the
 * values here, every call site keeps using `<Icon name="..." />`.
 */
export const icons = {
  'alert-triangle': TriangleAlert,
  area: Mountain,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up-down': ArrowUpDown,
  'at-sign': AtSign,
  block: Stone,
  bold: Bold,
  bookmark: Bookmark,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  close: X,
  code: Code,
  copy: Copy,
  edit: SquarePen,
  eye: Eye,
  'eye-off': EyeOff,
  'file-text': FileText,
  filter: ListFilter,
  'grip-horizontal': GripHorizontal,
  'grip-vertical': GripVertical,
  history: History,
  image: Image,
  'image-off': ImageOff,
  info: Info,
  italic: Italic,
  layers: Layers,
  link: Link,
  list: List,
  locate: LocateFixed,
  lock: Lock,
  'log-out': LogOut,
  map: Map,
  'map-pin': MapPin,
  'map-pin-search': MapPinSearch,
  'map-pin-x': MapPinX,
  maximize: Maximize2,
  minimize: Minimize2,
  minus: Minus,
  more: Ellipsis,
  mountain: Mountain,
  navigation: Navigation,
  'no-signal': WifiOff,
  parking: SquareParking,
  pause: Pause,
  pickaxe: Pickaxe,
  play: Play,
  plus: Plus,
  redo: Redo2,
  route: Route,
  search: Search,
  settings: Settings,
  share: Share,
  smartphone: Smartphone,
  star: Star,
  sync: RefreshCw,
  'tent-tree': TentTree,
  trash: Trash2,
  'trending-up': TrendingUp,
  undo: Undo2,
  user: User,
  users: Users,
  'users-round': UsersRound,
  'volume-1': Volume1,
  'volume-off': VolumeX,
} satisfies Record<string, Component<IconProps>>

export type IconName = keyof typeof icons
