ALTER POLICY "region.read can insert activities" ON "activities" TO authenticated WITH CHECK ((SELECT authorize_in_region('region.read', "activities"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.read can read activities" ON "activities" TO authenticated USING ((SELECT authorize_in_region('region.read', "activities"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.delete can delete activities" ON "activities" TO authenticated USING ((SELECT authorize_in_region('region.delete', "activities"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.read can delete their own activities" ON "activities" TO authenticated USING (EXISTS (SELECT 1 FROM public.users u WHERE u.id = "activities"."user_fk" AND u.auth_user_fk = (SELECT auth.uid())) AND (SELECT authorize_in_region('region.read', "activities"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.read can update their own activities" ON "activities" TO authenticated USING (EXISTS (SELECT 1 FROM public.users u WHERE u.id = "activities"."user_fk" AND u.auth_user_fk = (SELECT auth.uid())) AND (SELECT authorize_in_region('region.read', "activities"."region_fk"))) WITH CHECK (EXISTS (SELECT 1 FROM public.users u WHERE u.id = "activities"."user_fk" AND u.auth_user_fk = (SELECT auth.uid())) AND (SELECT authorize_in_region('region.read', "activities"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.read can read areas" ON "areas" TO authenticated USING ((SELECT authorize_in_region('region.read', "areas"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.edit can insert areas" ON "areas" TO authenticated WITH CHECK ((SELECT authorize_in_region('region.edit', "areas"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.edit can update areas" ON "areas" TO authenticated USING ((SELECT authorize_in_region('region.edit', "areas"."region_fk"))) WITH CHECK ((SELECT authorize_in_region('region.edit', "areas"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.delete can delete areas" ON "areas" TO authenticated USING ((SELECT authorize_in_region('region.delete', "areas"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.edit can delete areas" ON "areas" TO authenticated USING ((SELECT authorize_in_region('region.edit', "areas"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.read can insert ascents" ON "ascents" TO authenticated WITH CHECK ((SELECT authorize_in_region('region.read', "ascents"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.read can read ascents" ON "ascents" TO authenticated USING ((SELECT authorize_in_region('region.read', "ascents"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.admin can fully access ascents" ON "ascents" TO authenticated USING ((SELECT authorize_in_region('region.admin', "ascents"."region_fk"))) WITH CHECK ((SELECT authorize_in_region('region.admin', "ascents"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.read can read blocks" ON "blocks" TO authenticated USING ((SELECT authorize_in_region('region.read', "blocks"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.edit can insert blocks" ON "blocks" TO authenticated WITH CHECK ((SELECT authorize_in_region('region.edit', "blocks"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.edit can update blocks" ON "blocks" TO authenticated USING ((SELECT authorize_in_region('region.edit', "blocks"."region_fk"))) WITH CHECK ((SELECT authorize_in_region('region.edit', "blocks"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.delete can delete blocks" ON "blocks" TO authenticated USING ((SELECT authorize_in_region('region.delete', "blocks"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.edit can delete blocks" ON "blocks" TO authenticated USING ((SELECT authorize_in_region('region.edit', "blocks"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.read can insert bunny_streams" ON "bunny_streams" TO authenticated WITH CHECK ((SELECT authorize_in_region('region.read', "bunny_streams"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.read can read bunny_streams" ON "bunny_streams" TO authenticated USING ((SELECT authorize_in_region('region.read', "bunny_streams"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.edit can update bunny_streams" ON "bunny_streams" TO authenticated USING ((SELECT authorize_in_region('region.edit', "bunny_streams"."region_fk"))) WITH CHECK ((SELECT authorize_in_region('region.edit', "bunny_streams"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.edit can delete bunny_streams" ON "bunny_streams" TO authenticated USING ((SELECT authorize_in_region('region.edit', "bunny_streams"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.admin can fully access bunny_streams" ON "bunny_streams" TO authenticated USING ((SELECT authorize_in_region('region.admin', "bunny_streams"."region_fk"))) WITH CHECK ((SELECT authorize_in_region('region.admin', "bunny_streams"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.read can insert changes on their own events" ON "changes" TO authenticated WITH CHECK (EXISTS (SELECT 1 FROM public.events e JOIN public.users u ON u.id = e.actor_fk WHERE e.id = "changes"."event_fk" AND u.auth_user_fk = (SELECT auth.uid()) AND e.region_fk = "changes"."region_fk") AND (SELECT authorize_in_region('region.read', "changes"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.read can read changes" ON "changes" TO authenticated USING ((SELECT authorize_in_region('region.read', "changes"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.read can update changes on their own events" ON "changes" TO authenticated USING (EXISTS (SELECT 1 FROM public.events e JOIN public.users u ON u.id = e.actor_fk WHERE e.id = "changes"."event_fk" AND u.auth_user_fk = (SELECT auth.uid()) AND e.region_fk = "changes"."region_fk") AND (SELECT authorize_in_region('region.read', "changes"."region_fk"))) WITH CHECK (EXISTS (SELECT 1 FROM public.events e JOIN public.users u ON u.id = e.actor_fk WHERE e.id = "changes"."event_fk" AND u.auth_user_fk = (SELECT auth.uid()) AND e.region_fk = "changes"."region_fk") AND (SELECT authorize_in_region('region.read', "changes"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.read can delete changes on their own events" ON "changes" TO authenticated USING (EXISTS (SELECT 1 FROM public.events e JOIN public.users u ON u.id = e.actor_fk WHERE e.id = "changes"."event_fk" AND u.auth_user_fk = (SELECT auth.uid()) AND e.region_fk = "changes"."region_fk") AND (SELECT authorize_in_region('region.read', "changes"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.read can insert their own events" ON "events" TO authenticated WITH CHECK (EXISTS (SELECT 1 FROM public.users u WHERE u.id = "events"."actor_fk" AND u.auth_user_fk = (SELECT auth.uid())) AND (SELECT authorize_in_region('region.read', "events"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.read can read events" ON "events" TO authenticated USING ((SELECT authorize_in_region('region.read', "events"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.read can update their own events" ON "events" TO authenticated USING (EXISTS (SELECT 1 FROM public.users u WHERE u.id = "events"."actor_fk" AND u.auth_user_fk = (SELECT auth.uid())) AND (SELECT authorize_in_region('region.read', "events"."region_fk"))) WITH CHECK (EXISTS (SELECT 1 FROM public.users u WHERE u.id = "events"."actor_fk" AND u.auth_user_fk = (SELECT auth.uid())) AND (SELECT authorize_in_region('region.read', "events"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.read can delete their own events" ON "events" TO authenticated USING (EXISTS (SELECT 1 FROM public.users u WHERE u.id = "events"."actor_fk" AND u.auth_user_fk = (SELECT auth.uid())) AND (SELECT authorize_in_region('region.read', "events"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.delete can delete events" ON "events" TO authenticated USING ((SELECT authorize_in_region('region.delete', "events"."region_fk")));--> statement-breakpoint
ALTER POLICY "users can insert own favorites" ON "favorites" TO authenticated WITH CHECK ((SELECT auth.uid()) = "favorites"."auth_user_fk");--> statement-breakpoint
ALTER POLICY "region.read can read favorites" ON "favorites" TO authenticated USING ((SELECT authorize_in_region('region.read', "favorites"."region_fk")));--> statement-breakpoint
ALTER POLICY "users can delete own favorites" ON "favorites" TO authenticated USING ((SELECT auth.uid()) = "favorites"."auth_user_fk");--> statement-breakpoint
ALTER POLICY "region.read can insert files" ON "files" TO authenticated WITH CHECK ((SELECT authorize_in_region('region.read', "files"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.read can read files" ON "files" TO authenticated USING ((SELECT authorize_in_region('region.read', "files"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.edit can update files" ON "files" TO authenticated USING ((SELECT authorize_in_region('region.edit', "files"."region_fk"))) WITH CHECK ((SELECT authorize_in_region('region.edit', "files"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.edit can delete files" ON "files" TO authenticated USING ((SELECT authorize_in_region('region.edit', "files"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.read can fully access first_ascensionists" ON "first_ascensionists" TO authenticated USING ((SELECT authorize_in_region('region.read', "first_ascensionists"."region_fk"))) WITH CHECK ((SELECT authorize_in_region('region.read', "first_ascensionists"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.read can read geolocations" ON "geolocations" TO authenticated USING ((SELECT authorize_in_region('region.read', "geolocations"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.edit can insert geolocations" ON "geolocations" TO authenticated WITH CHECK ((SELECT authorize_in_region('region.edit', "geolocations"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.edit can update geolocations" ON "geolocations" TO authenticated USING ((SELECT authorize_in_region('region.edit', "geolocations"."region_fk"))) WITH CHECK ((SELECT authorize_in_region('region.edit', "geolocations"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.delete can delete geolocations" ON "geolocations" TO authenticated USING ((SELECT authorize_in_region('region.delete', "geolocations"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.read can insert geolocations" ON "geolocations" TO authenticated WITH CHECK ((SELECT authorize_in_region('region.read', "geolocations"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.edit can delete geolocations" ON "geolocations" TO authenticated USING ((SELECT authorize_in_region('region.edit', "geolocations"."region_fk")));--> statement-breakpoint
ALTER POLICY "users can update own notifications" ON "notifications" TO authenticated USING ((SELECT auth.uid()) = "notifications"."auth_user_fk") WITH CHECK ((SELECT auth.uid()) = "notifications"."auth_user_fk");--> statement-breakpoint
ALTER POLICY "users can delete own push_subscriptions" ON "push_subscriptions" TO authenticated USING ((SELECT auth.uid()) = "push_subscriptions"."auth_user_fk");--> statement-breakpoint
ALTER POLICY "users can insert own push_subscriptions" ON "push_subscriptions" TO authenticated WITH CHECK ((SELECT auth.uid()) = "push_subscriptions"."auth_user_fk");--> statement-breakpoint
ALTER POLICY "users can read own push_subscriptions" ON "push_subscriptions" TO authenticated USING ((SELECT auth.uid()) = "push_subscriptions"."auth_user_fk");--> statement-breakpoint
ALTER POLICY "users can update own push_subscriptions" ON "push_subscriptions" TO authenticated USING ((SELECT auth.uid()) = "push_subscriptions"."auth_user_fk") WITH CHECK ((SELECT auth.uid()) = "push_subscriptions"."auth_user_fk");--> statement-breakpoint
ALTER POLICY "users can insert own reactions" ON "reactions" TO authenticated WITH CHECK ((SELECT auth.uid()) = "reactions"."auth_user_fk" AND EXISTS (SELECT 1 FROM public.users u WHERE u.id = "reactions"."user_fk" AND u.auth_user_fk = (SELECT auth.uid())) AND EXISTS (SELECT 1 FROM public.events e WHERE e.id = "reactions"."event_fk" AND e.region_fk = "reactions"."region_fk") AND (SELECT authorize_in_region('region.read', "reactions"."region_fk")));--> statement-breakpoint
ALTER POLICY "users can update own reactions" ON "reactions" TO authenticated USING ((SELECT auth.uid()) = "reactions"."auth_user_fk" AND EXISTS (SELECT 1 FROM public.users u WHERE u.id = "reactions"."user_fk" AND u.auth_user_fk = (SELECT auth.uid())) AND EXISTS (SELECT 1 FROM public.events e WHERE e.id = "reactions"."event_fk" AND e.region_fk = "reactions"."region_fk") AND (SELECT authorize_in_region('region.read', "reactions"."region_fk"))) WITH CHECK ((SELECT auth.uid()) = "reactions"."auth_user_fk" AND EXISTS (SELECT 1 FROM public.users u WHERE u.id = "reactions"."user_fk" AND u.auth_user_fk = (SELECT auth.uid())) AND EXISTS (SELECT 1 FROM public.events e WHERE e.id = "reactions"."event_fk" AND e.region_fk = "reactions"."region_fk") AND (SELECT authorize_in_region('region.read', "reactions"."region_fk")));--> statement-breakpoint
ALTER POLICY "users can delete own reactions" ON "reactions" TO authenticated USING ((SELECT auth.uid()) = "reactions"."auth_user_fk" AND EXISTS (SELECT 1 FROM public.users u WHERE u.id = "reactions"."user_fk" AND u.auth_user_fk = (SELECT auth.uid())) AND EXISTS (SELECT 1 FROM public.events e WHERE e.id = "reactions"."event_fk" AND e.region_fk = "reactions"."region_fk") AND (SELECT authorize_in_region('region.read', "reactions"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.read can read reactions" ON "reactions" TO authenticated USING ((SELECT authorize_in_region('region.read', "reactions"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.delete can delete reactions" ON "reactions" TO authenticated USING ((SELECT authorize_in_region('region.delete', "reactions"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.admin can insert region_invitations" ON "region_invitations" TO authenticated WITH CHECK ((SELECT authorize_in_region('region.admin', "region_invitations"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.admin can update region_invitations" ON "region_invitations" TO authenticated USING ((SELECT authorize_in_region('region.admin', "region_invitations"."region_fk"))) WITH CHECK ((SELECT authorize_in_region('region.admin', "region_invitations"."region_fk")));--> statement-breakpoint
ALTER POLICY "region members can read region_invitations" ON "region_invitations" TO authenticated USING ((SELECT authorize_in_region('region.read', "region_invitations"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.admin can manage region_members" ON "region_members" TO authenticated USING ((SELECT authorize_in_region('region.admin', "region_members"."region_fk"))) WITH CHECK ((SELECT authorize_in_region('region.admin', "region_members"."region_fk")) AND EXISTS (SELECT 1 FROM public.users u WHERE u.id = "region_members"."user_fk" AND u.auth_user_fk = "region_members"."auth_user_fk"));--> statement-breakpoint
ALTER POLICY "region.read can read region_members" ON "region_members" TO authenticated USING ((SELECT authorize_in_region('region.read', "region_members"."region_fk")));--> statement-breakpoint
ALTER POLICY "users can delete own region_members" ON "region_members" TO authenticated USING ((SELECT auth.uid()) = "region_members"."auth_user_fk");--> statement-breakpoint
ALTER POLICY "region.admin can update regions they administer" ON "regions" TO authenticated USING ((SELECT authorize_in_region('region.admin', "regions"."id"))) WITH CHECK ((SELECT authorize_in_region('region.admin', "regions"."id")));--> statement-breakpoint
ALTER POLICY "region.read can read route_external_resource_27crags" ON "route_external_resource_27crags" TO authenticated USING ((SELECT authorize_in_region('region.read', "route_external_resource_27crags"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.delete can delete route_external_resource_27crags" ON "route_external_resource_27crags" TO authenticated USING ((SELECT authorize_in_region('region.delete', "route_external_resource_27crags"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.read can read route_external_resource_8a" ON "route_external_resource_8a" TO authenticated USING ((SELECT authorize_in_region('region.read', "route_external_resource_8a"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.delete can delete route_external_resource_8a" ON "route_external_resource_8a" TO authenticated USING ((SELECT authorize_in_region('region.delete', "route_external_resource_8a"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.read can read route_external_resource_the_crag" ON "route_external_resource_the_crag" TO authenticated USING ((SELECT authorize_in_region('region.read', "route_external_resource_the_crag"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.delete can delete route_external_resource_the_crag" ON "route_external_resource_the_crag" TO authenticated USING ((SELECT authorize_in_region('region.delete', "route_external_resource_the_crag"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.read can read route_external_resources" ON "route_external_resources" TO authenticated USING ((SELECT authorize_in_region('region.read', "route_external_resources"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.edit can update route_external_resources" ON "route_external_resources" TO authenticated USING ((SELECT authorize_in_region('region.edit', "route_external_resources"."region_fk"))) WITH CHECK ((SELECT authorize_in_region('region.edit', "route_external_resources"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.delete can delete route_external_resources" ON "route_external_resources" TO authenticated USING ((SELECT authorize_in_region('region.delete', "route_external_resources"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.read can read routes" ON "routes" TO authenticated USING ((SELECT authorize_in_region('region.read', "routes"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.edit can insert routes" ON "routes" TO authenticated WITH CHECK ((SELECT authorize_in_region('region.edit', "routes"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.edit can update routes" ON "routes" TO authenticated USING ((SELECT authorize_in_region('region.edit', "routes"."region_fk"))) WITH CHECK ((SELECT authorize_in_region('region.edit', "routes"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.delete can delete routes" ON "routes" TO authenticated USING ((SELECT authorize_in_region('region.delete', "routes"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.edit can delete routes" ON "routes" TO authenticated USING ((SELECT authorize_in_region('region.edit', "routes"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.read can update routes" ON "routes" TO authenticated USING ((SELECT authorize_in_region('region.read', "routes"."region_fk"))) WITH CHECK ((SELECT authorize_in_region('region.read', "routes"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.read can fully access routes_to_first_ascensionists" ON "routes_to_first_ascensionists" TO authenticated USING ((SELECT authorize_in_region('region.read', "routes_to_first_ascensionists"."region_fk"))) WITH CHECK ((SELECT authorize_in_region('region.read', "routes_to_first_ascensionists"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.read can read routes_to_tags" ON "routes_to_tags" TO authenticated USING ((SELECT authorize_in_region('region.read', "routes_to_tags"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.edit can insert routes_to_tags" ON "routes_to_tags" TO authenticated WITH CHECK ((SELECT authorize_in_region('region.edit', "routes_to_tags"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.edit can update routes_to_tags" ON "routes_to_tags" TO authenticated USING ((SELECT authorize_in_region('region.edit', "routes_to_tags"."region_fk"))) WITH CHECK ((SELECT authorize_in_region('region.edit', "routes_to_tags"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.delete can delete routes_to_tags" ON "routes_to_tags" TO authenticated USING ((SELECT authorize_in_region('region.delete', "routes_to_tags"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.edit can delete routes_to_tags" ON "routes_to_tags" TO authenticated USING ((SELECT authorize_in_region('region.edit', "routes_to_tags"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.read can read topo_routes" ON "topo_routes" TO authenticated USING ((SELECT authorize_in_region('region.read', "topo_routes"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.edit can insert topo_routes" ON "topo_routes" TO authenticated WITH CHECK ((SELECT authorize_in_region('region.edit', "topo_routes"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.edit can update topo_routes" ON "topo_routes" TO authenticated USING ((SELECT authorize_in_region('region.edit', "topo_routes"."region_fk"))) WITH CHECK ((SELECT authorize_in_region('region.edit', "topo_routes"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.delete can delete topo_routes" ON "topo_routes" TO authenticated USING ((SELECT authorize_in_region('region.delete', "topo_routes"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.edit can delete topo_routes" ON "topo_routes" TO authenticated USING ((SELECT authorize_in_region('region.edit', "topo_routes"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.read can read topos" ON "topos" TO authenticated USING ((SELECT authorize_in_region('region.read', "topos"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.edit can insert topos" ON "topos" TO authenticated WITH CHECK ((SELECT authorize_in_region('region.edit', "topos"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.edit can update topos" ON "topos" TO authenticated USING ((SELECT authorize_in_region('region.edit', "topos"."region_fk"))) WITH CHECK ((SELECT authorize_in_region('region.edit', "topos"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.delete can delete topos" ON "topos" TO authenticated USING ((SELECT authorize_in_region('region.delete', "topos"."region_fk")));--> statement-breakpoint
ALTER POLICY "region.edit can delete topos" ON "topos" TO authenticated USING ((SELECT authorize_in_region('region.edit', "topos"."region_fk")));--> statement-breakpoint
ALTER POLICY "users can read own user_roles" ON "user_roles" TO authenticated USING ((SELECT auth.uid()) = "user_roles"."auth_user_fk");--> statement-breakpoint
ALTER POLICY "users can insert own users_settings" ON "user_settings" TO authenticated WITH CHECK ((SELECT auth.uid()) = "user_settings"."auth_user_fk");--> statement-breakpoint
ALTER POLICY "users can read own users_settings" ON "user_settings" TO authenticated USING ((SELECT auth.uid()) = "user_settings"."auth_user_fk");--> statement-breakpoint
ALTER POLICY "users can update own users_settings" ON "user_settings" TO authenticated USING ((SELECT auth.uid()) = "user_settings"."auth_user_fk") WITH CHECK ((SELECT auth.uid()) = "user_settings"."auth_user_fk");--> statement-breakpoint
ALTER POLICY "users can update own users" ON "users" TO authenticated USING ((SELECT auth.uid()) = "users"."auth_user_fk") WITH CHECK ((SELECT auth.uid()) = "users"."auth_user_fk");