#!/usr/bin/env node
// Bitwarden Secrets Manager glue for the three environments.
//
// Which environment a run touches is decided by BWS_ACCESS_TOKEN and nothing else: each machine
// account (grnyte-dev / grnyte-demo / grnyte-prod) is granted exactly one project, so no project
// id, no environment name and no per-environment branch ever appears in this file. Point the token
// at demo and every command below talks to demo.
//
// deployment/SECRETS.md has the one-time setup.
//
//   node deployment/secrets.mjs pull [file]              rewrite .env from the project
//   node deployment/secrets.mjs vercel <project> [target] push the project to a Vercel project
//   node deployment/secrets.mjs seed <file>              create/update secrets from a local .env
//   node deployment/secrets.mjs selftest                 assert the .env writer, no network

import { spawnSync } from 'node:child_process'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'

const HEADER = '# Generated by deployment/secrets.mjs from Bitwarden. Do not edit, do not commit.'

// dotenv (drizzle.config.ts) unescapes only \n and \r, while Vite's loader also unescapes \$. No
// escaping of ", \ or $ is read back the same way by both, so a value containing one cannot be
// written to a .env at all. Refusing beats handing drizzle a corrupted DATABASE_URL.
const UNWRITABLE = /["\\$\n\r]/

const die = (message) => {
  console.error(message)
  process.exit(1)
}

const run = (command, args, input) => {
  const result = spawnSync(command, args, { encoding: 'utf8', input, stdio: ['pipe', 'pipe', 'inherit'] })

  if (result.error?.code === 'ENOENT') {
    die(
      command === 'bws'
        ? 'bws not found. Install it with: curl https://bws.bitwarden.com/install | sh'
        : `${command} not found`,
    )
  }
  if (result.status !== 0) {
    die(`${command} ${args.slice(0, 2).join(' ')} failed (exit ${result.status})`)
  }

  return result.stdout
}

// -c no keeps bws from pretty-printing the JSON through bat when a TTY is attached.
const bws = (args, input) => {
  // bws answers an empty token with "Doesn't contain a decryption key", which sends you looking at
  // the wrong thing. The usual cause is a token that came from a shell function: npm runs scripts
  // with sh, where nothing from your .zshrc exists.
  if (!process.env.BWS_ACCESS_TOKEN) {
    die('BWS_ACCESS_TOKEN is empty. It is what picks the environment, so nothing runs without it.')
  }

  return run('bws', ['-c', 'no', ...args], input)
}

const listSecrets = () => JSON.parse(bws(['secret', 'list', '-o', 'json'])).sort((a, b) => a.key.localeCompare(b.key))

const render = (secrets) => [HEADER, ...secrets.map((secret) => `${secret.key}="${secret.value}"`), ''].join('\n')

// The project holds one environment's whole world, and this prefix is the seam through it: ZERO_* is
// the Zero server's half. deploy-zero.yml sends exactly those to the VPS, so exactly those stay off
// Vercel. The app reads PUBLIC_ZERO_URL and nothing else about Zero.
const isZeroServerOnly = (key) => key.startsWith('ZERO_')

function pull(file = '.env', force = false) {
  const secrets = listSecrets()
  if (secrets.length === 0) {
    die('This access token can read no secrets. Check the machine account has the project assigned.')
  }

  const unwritable = secrets.filter((secret) => UNWRITABLE.test(secret.value))
  if (unwritable.length > 0) {
    die(
      `Cannot write ${unwritable.map((secret) => secret.key).join(', ')}: the value contains " \\ $ or a newline, ` +
        'which a .env cannot round-trip. Change the value, or run the command under `bws run -- <command>` instead, ' +
        'which passes secrets as real environment variables.',
    )
  }

  // A .env that this script did not write is somebody's hand-tuned file. Losing it is not worth the
  // convenience of an unconditional overwrite.
  if (existsSync(file) && !readFileSync(file, 'utf8').startsWith(HEADER) && !force) {
    die(`${file} was not generated by this script. Move it aside, or re-run with --force.`)
  }

  writeFileSync(file, render(secrets), { mode: 0o600 })
  console.error(`Wrote ${secrets.length} secrets to ${file}`)
}

function pushToVercel(project, target = 'production') {
  if (project == null) die('Usage: node deployment/secrets.mjs vercel <vercel-project> [target]')

  for (const secret of listSecrets().filter((secret) => !isZeroServerOnly(secret.key))) {
    // Vercel rejects --sensitive for development, and a sensitive PUBLIC_* var only means nobody can
    // read a value in the dashboard that ships to the browser anyway.
    const sensitivity =
      target === 'development' ? [] : [secret.key.startsWith('PUBLIC_') ? '--no-sensitive' : '--sensitive']

    run('vercel', ['env', 'add', secret.key, target, '--force', '--project', project, ...sensitivity], secret.value)
    console.error(`${project}/${target}: ${secret.key}`)
  }
}

async function seed(file) {
  if (file == null) die('Usage: node deployment/secrets.mjs seed <file>')
  if (!existsSync(file)) {
    die(`${file} does not exist. seed reads a local .env into Bitwarden; pull is the other direction.`)
  }

  const { parse } = await import('dotenv')
  const projects = JSON.parse(bws(['project', 'list', '-o', 'json']))
  if (projects.length !== 1) {
    die(`This access token can see ${projects.length} projects. Seeding needs a token scoped to exactly one.`)
  }

  const existing = new Map(listSecrets().map((secret) => [secret.key, secret.id]))
  const wanted = Object.entries(parse(readFileSync(file)))
  if (wanted.length === 0) die(`${file} holds no variables, so there is nothing to seed.`)

  for (const [key, value] of wanted) {
    if (value === '') {
      console.error(`skipped ${key} (empty)`)
      continue
    }

    // ponytail: bws takes the value as an argv, so it is visible in `ps` while this runs. Fine on a
    // laptop, not on a shared host.
    if (existing.has(key)) {
      bws(['secret', 'edit', existing.get(key), '--value', value])
      console.error(`updated ${key}`)
    } else {
      bws(['secret', 'create', key, value, projects[0].id])
      console.error(`created ${key}`)
    }
  }
}

async function selftest() {
  const { parse } = await import('dotenv')
  const { strict: assert } = await import('node:assert')

  const roundTrip = (value) => parse(render([{ key: 'K', value }])).K

  assert.equal(roundTrip('plain'), 'plain')
  assert.equal(roundTrip('with spaces'), 'with spaces')
  assert.equal(roundTrip('has#hash'), 'has#hash')
  assert.equal(roundTrip('a=b=c'), 'a=b=c')
  assert.equal(roundTrip("it's fine"), "it's fine")
  assert.equal(roundTrip('postgres://u:p@h:5432/db?x=1'), 'postgres://u:p@h:5432/db?x=1')
  assert.equal(roundTrip(''), '')

  // The characters pull refuses. What each one comes back as depends on the reader (Vite expands $,
  // dotenv does not; escaping fixes one and breaks the other, and a literal newline survives dotenv
  // but not docker compose's env_file or the grep in deploy-zero.yml), so the assertion is that they
  // are refused, not what any one parser makes of them.
  for (const value of ['say "hi"', 'a\\b', 'a$B', 'two\nlines']) {
    assert.ok(UNWRITABLE.test(value), `${JSON.stringify(value)} should be refused`)
  }

  assert.ok(render([{ key: 'K', value: 'v' }]).startsWith(HEADER))

  // The Vercel/VPS seam, in both directions: what one side keeps, the other drops.
  assert.deepEqual(
    ['ZERO_UPSTREAM_DB', 'ZERO_AUTH_SECRET', 'PUBLIC_ZERO_URL', 'DATABASE_URL'].filter(isZeroServerOnly),
    ['ZERO_UPSTREAM_DB', 'ZERO_AUTH_SECRET'],
  )

  console.error('selftest ok')
}

const [command, ...rest] = process.argv.slice(2)
const args = rest.filter((arg) => arg !== '--force')

switch (command) {
  case 'pull':
    pull(args[0], rest.includes('--force'))
    break
  case 'vercel':
    pushToVercel(args[0], args[1])
    break
  case 'seed':
    await seed(args[0])
    break
  case 'selftest':
    await selftest()
    break
  default:
    die(
      [
        'node deployment/secrets.mjs pull [file] [--force]      rewrite .env from the project',
        'node deployment/secrets.mjs vercel <project> [target]  push the project to a Vercel project',
        'node deployment/secrets.mjs seed <file>                create/update secrets from a local .env',
        'node deployment/secrets.mjs selftest                   assert the .env writer, no network',
      ].join('\n'),
    )
}
