// @generated drizzle-zero signature:sha256:72ebd0b23597eb5c903f2259ba44ebf626ec32e738bf7baac40f4a7df1a4e938
// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.

import type { Row } from '@rocicorp/zero'
import { createBuilder } from '@rocicorp/zero'
import type { CustomType } from 'drizzle-zero'
import type * as drizzleSchema from '../db/schema'

const activitiesTable = {
  columns: {
    columnName: {
      customType: null as unknown as string,
      optional: true,
      serverName: 'column_name',
      type: 'string',
    },
    createdAt: {
      customType: null as unknown as number,
      optional: true,
      serverName: 'created_at',
      type: 'number',
    },
    entityId: {
      customType: null as unknown as string,
      optional: false,
      serverName: 'entity_id',
      type: 'string',
    },
    entityType: {
      customType: null as unknown as 'area' | 'ascent' | 'block' | 'file' | 'route' | 'user',
      optional: false,
      serverName: 'entity_type',
      type: 'string',
    },
    id: {
      customType: null as unknown as number,
      optional: false,
      type: 'number',
    },
    metadata: {
      customType: null as unknown as string,
      optional: true,
      type: 'string',
    },
    newValue: {
      customType: null as unknown as string,
      optional: true,
      serverName: 'new_value',
      type: 'string',
    },
    notified: {
      customType: null as unknown as boolean,
      optional: true,
      type: 'boolean',
    },
    oldValue: {
      customType: null as unknown as string,
      optional: true,
      serverName: 'old_value',
      type: 'string',
    },
    parentEntityId: {
      customType: null as unknown as string,
      optional: true,
      serverName: 'parent_entity_id',
      type: 'string',
    },
    parentEntityType: {
      customType: null as unknown as 'area' | 'ascent' | 'block' | 'route',
      optional: true,
      serverName: 'parent_entity_type',
      type: 'string',
    },
    regionFk: {
      customType: null as unknown as number,
      optional: false,
      serverName: 'region_fk',
      type: 'number',
    },
    type: {
      customType: null as unknown as 'created' | 'deleted' | 'updated' | 'uploaded',
      optional: false,
      type: 'string',
    },
    userFk: {
      customType: null as unknown as number,
      optional: false,
      serverName: 'user_fk',
      type: 'number',
    },
  },
  name: 'activities',
  primaryKey: ['id'],
} as const
const areasTable = {
  columns: {
    createdAt: {
      customType: null as unknown as number,
      optional: true,
      serverName: 'created_at',
      type: 'number',
    },
    createdBy: {
      customType: null as unknown as number,
      optional: false,
      serverName: 'created_by',
      type: 'number',
    },
    deletedAt: {
      customType: null as unknown as number,
      optional: true,
      serverName: 'deleted_at',
      type: 'number',
    },
    description: {
      customType: null as unknown as string,
      optional: true,
      type: 'string',
    },
    geoPaths: {
      customType: null as unknown as string[],
      optional: true,
      serverName: 'geo_paths',
      type: 'json',
    },
    id: {
      customType: null as unknown as number,
      optional: false,
      type: 'number',
    },
    name: {
      customType: null as unknown as string,
      optional: false,
      type: 'string',
    },
    parentFk: {
      customType: null as unknown as number,
      optional: true,
      serverName: 'parent_fk',
      type: 'number',
    },
    regionFk: {
      customType: null as unknown as number,
      optional: false,
      serverName: 'region_fk',
      type: 'number',
    },
    type: {
      customType: null as unknown as 'area' | 'crag',
      optional: true,
      type: 'string',
    },
    walkingPaths: {
      customType: null as unknown as string[],
      optional: true,
      serverName: 'walking_paths',
      type: 'json',
    },
  },
  name: 'areas',
  primaryKey: ['id'],
} as const
const ascentsTable = {
  columns: {
    createdAt: {
      customType: null as unknown as number,
      optional: true,
      serverName: 'created_at',
      type: 'number',
    },
    createdBy: {
      customType: null as unknown as number,
      optional: false,
      serverName: 'created_by',
      type: 'number',
    },
    dateTime: {
      customType: null as unknown as number,
      optional: true,
      serverName: 'date_time',
      type: 'number',
    },
    gradeFk: {
      customType: null as unknown as number,
      optional: true,
      serverName: 'grade_fk',
      type: 'number',
    },
    humidity: {
      customType: null as unknown as number,
      optional: true,
      type: 'number',
    },
    id: {
      customType: null as unknown as number,
      optional: false,
      type: 'number',
    },
    notes: {
      customType: null as unknown as string,
      optional: true,
      type: 'string',
    },
    rating: {
      customType: null as unknown as number,
      optional: true,
      type: 'number',
    },
    regionFk: {
      customType: null as unknown as number,
      optional: false,
      serverName: 'region_fk',
      type: 'number',
    },
    routeFk: {
      customType: null as unknown as number,
      optional: false,
      serverName: 'route_fk',
      type: 'number',
    },
    temperature: {
      customType: null as unknown as number,
      optional: true,
      type: 'number',
    },
    type: {
      customType: null as unknown as 'attempt' | 'flash' | 'repeat' | 'send',
      optional: false,
      type: 'string',
    },
  },
  name: 'ascents',
  primaryKey: ['id'],
} as const
const blocksTable = {
  columns: {
    areaFk: {
      customType: null as unknown as number,
      optional: false,
      serverName: 'area_fk',
      type: 'number',
    },
    createdAt: {
      customType: null as unknown as number,
      optional: true,
      serverName: 'created_at',
      type: 'number',
    },
    createdBy: {
      customType: null as unknown as number,
      optional: false,
      serverName: 'created_by',
      type: 'number',
    },
    deletedAt: {
      customType: null as unknown as number,
      optional: true,
      serverName: 'deleted_at',
      type: 'number',
    },
    geolocationFk: {
      customType: null as unknown as number,
      optional: true,
      serverName: 'geolocation_fk',
      type: 'number',
    },
    id: {
      customType: null as unknown as number,
      optional: false,
      type: 'number',
    },
    name: {
      customType: null as unknown as string,
      optional: false,
      type: 'string',
    },
    order: {
      customType: null as unknown as number,
      optional: false,
      type: 'number',
    },
    regionFk: {
      customType: null as unknown as number,
      optional: false,
      serverName: 'region_fk',
      type: 'number',
    },
  },
  name: 'blocks',
  primaryKey: ['id'],
} as const
const bunnyStreamsTable = {
  columns: {
    fileFk: {
      customType: null as unknown as string,
      optional: true,
      serverName: 'file_fk',
      type: 'string',
    },
    id: {
      customType: null as unknown as string,
      optional: false,
      type: 'string',
    },
    regionFk: {
      customType: null as unknown as number,
      optional: false,
      serverName: 'region_fk',
      type: 'number',
    },
    source: {
      customType: null as unknown as string,
      optional: true,
      type: 'string',
    },
  },
  name: 'bunnyStreams',
  primaryKey: ['id'],
  serverName: 'bunny_streams',
} as const
const clientErrorLogsTable = {
  columns: {
    createdAt: {
      customType: null as unknown as number,
      optional: true,
      serverName: 'created_at',
      type: 'number',
    },
    createdBy: {
      customType: null as unknown as number,
      optional: true,
      serverName: 'created_by',
      type: 'number',
    },
    error: {
      customType: null as unknown as string,
      optional: true,
      type: 'string',
    },
    id: {
      customType: null as unknown as number,
      optional: false,
      type: 'number',
    },
    navigator: {
      customType: null as unknown as CustomType<typeof drizzleSchema, 'clientErrorLogs', 'navigator'>,
      optional: true,
      type: 'json',
    },
    pathname: {
      customType: null as unknown as string,
      optional: true,
      type: 'string',
    },
  },
  name: 'clientErrorLogs',
  primaryKey: ['id'],
  serverName: 'client_error_logs',
} as const
const favoritesTable = {
  columns: {
    authUserFk: {
      customType: null as unknown as string,
      optional: false,
      serverName: 'auth_user_fk',
      type: 'string',
    },
    createdAt: {
      customType: null as unknown as number,
      optional: true,
      serverName: 'created_at',
      type: 'number',
    },
    entityId: {
      customType: null as unknown as string,
      optional: false,
      serverName: 'entity_id',
      type: 'string',
    },
    entityType: {
      customType: null as unknown as 'area' | 'block' | 'route',
      optional: false,
      serverName: 'entity_type',
      type: 'string',
    },
    id: {
      customType: null as unknown as number,
      optional: false,
      type: 'number',
    },
    regionFk: {
      customType: null as unknown as number,
      optional: false,
      serverName: 'region_fk',
      type: 'number',
    },
    userFk: {
      customType: null as unknown as number,
      optional: false,
      serverName: 'user_fk',
      type: 'number',
    },
  },
  name: 'favorites',
  primaryKey: ['id'],
} as const
const filesTable = {
  columns: {
    areaFk: {
      customType: null as unknown as number,
      optional: true,
      serverName: 'area_fk',
      type: 'number',
    },
    ascentFk: {
      customType: null as unknown as number,
      optional: true,
      serverName: 'ascent_fk',
      type: 'number',
    },
    blockFk: {
      customType: null as unknown as number,
      optional: true,
      serverName: 'block_fk',
      type: 'number',
    },
    bunnyStreamFk: {
      customType: null as unknown as string,
      optional: true,
      serverName: 'bunny_stream_fk',
      type: 'string',
    },
    createdAt: {
      customType: null as unknown as number,
      optional: true,
      serverName: 'created_at',
      type: 'number',
    },
    createdBy: {
      customType: null as unknown as number,
      optional: false,
      serverName: 'created_by',
      type: 'number',
    },
    height: {
      customType: null as unknown as number,
      optional: true,
      type: 'number',
    },
    id: {
      customType: null as unknown as string,
      optional: false,
      type: 'string',
    },
    path: {
      customType: null as unknown as string,
      optional: false,
      type: 'string',
    },
    regionFk: {
      customType: null as unknown as number,
      optional: false,
      serverName: 'region_fk',
      type: 'number',
    },
    routeFk: {
      customType: null as unknown as number,
      optional: true,
      serverName: 'route_fk',
      type: 'number',
    },
    visibility: {
      customType: null as unknown as 'private' | 'public',
      optional: true,
      type: 'string',
    },
    width: {
      customType: null as unknown as number,
      optional: true,
      type: 'number',
    },
  },
  name: 'files',
  primaryKey: ['id'],
} as const
const firstAscensionistsTable = {
  columns: {
    id: {
      customType: null as unknown as number,
      optional: false,
      type: 'number',
    },
    name: {
      customType: null as unknown as string,
      optional: false,
      type: 'string',
    },
    regionFk: {
      customType: null as unknown as number,
      optional: false,
      serverName: 'region_fk',
      type: 'number',
    },
    userFk: {
      customType: null as unknown as number,
      optional: true,
      serverName: 'user_fk',
      type: 'number',
    },
  },
  name: 'firstAscensionists',
  primaryKey: ['id'],
  serverName: 'first_ascensionists',
} as const
const geolocationsTable = {
  columns: {
    areaFk: {
      customType: null as unknown as number,
      optional: true,
      serverName: 'area_fk',
      type: 'number',
    },
    blockFk: {
      customType: null as unknown as number,
      optional: true,
      serverName: 'block_fk',
      type: 'number',
    },
    estimated: {
      customType: null as unknown as boolean,
      optional: true,
      type: 'boolean',
    },
    id: {
      customType: null as unknown as number,
      optional: false,
      type: 'number',
    },
    lat: {
      customType: null as unknown as number,
      optional: false,
      type: 'number',
    },
    long: {
      customType: null as unknown as number,
      optional: false,
      type: 'number',
    },
    regionFk: {
      customType: null as unknown as number,
      optional: false,
      serverName: 'region_fk',
      type: 'number',
    },
  },
  name: 'geolocations',
  primaryKey: ['id'],
} as const
const gradesTable = {
  columns: {
    FB: {
      customType: null as unknown as string,
      optional: true,
      type: 'string',
    },
    id: {
      customType: null as unknown as number,
      optional: false,
      type: 'number',
    },
    V: {
      customType: null as unknown as string,
      optional: true,
      type: 'string',
    },
  },
  name: 'grades',
  primaryKey: ['id'],
} as const
const pushSubscriptionsTable = {
  columns: {
    auth: {
      customType: null as unknown as string,
      optional: false,
      type: 'string',
    },
    authUserFk: {
      customType: null as unknown as string,
      optional: false,
      serverName: 'auth_user_fk',
      type: 'string',
    },
    endpoint: {
      customType: null as unknown as string,
      optional: false,
      type: 'string',
    },
    expirationTime: {
      customType: null as unknown as number,
      optional: true,
      serverName: 'expiration_time',
      type: 'number',
    },
    id: {
      customType: null as unknown as number,
      optional: false,
      type: 'number',
    },
    lang: {
      customType: null as unknown as string,
      optional: true,
      type: 'string',
    },
    p256dh: {
      customType: null as unknown as string,
      optional: false,
      type: 'string',
    },
    userFk: {
      customType: null as unknown as number,
      optional: false,
      serverName: 'user_fk',
      type: 'number',
    },
  },
  name: 'pushSubscriptions',
  primaryKey: ['id'],
  serverName: 'push_subscriptions',
} as const
const regionInvitationsTable = {
  columns: {
    acceptedAt: {
      customType: null as unknown as number,
      optional: true,
      serverName: 'accepted_at',
      type: 'number',
    },
    acceptedByFk: {
      customType: null as unknown as number,
      optional: true,
      serverName: 'accepted_by',
      type: 'number',
    },
    createdAt: {
      customType: null as unknown as number,
      optional: true,
      serverName: 'created_at',
      type: 'number',
    },
    email: {
      customType: null as unknown as string,
      optional: false,
      type: 'string',
    },
    expiresAt: {
      customType: null as unknown as number,
      optional: false,
      serverName: 'expires_at',
      type: 'number',
    },
    id: {
      customType: null as unknown as number,
      optional: false,
      type: 'number',
    },
    invitedByFk: {
      customType: null as unknown as number,
      optional: false,
      serverName: 'invited_by',
      type: 'number',
    },
    lastSentAt: {
      customType: null as unknown as number,
      optional: true,
      serverName: 'last_sent_at',
      type: 'number',
    },
    regionFk: {
      customType: null as unknown as number,
      optional: false,
      serverName: 'region_fk',
      type: 'number',
    },
    status: {
      customType: null as unknown as 'accepted' | 'expired' | 'pending',
      optional: true,
      type: 'string',
    },
    token: {
      customType: null as unknown as string,
      optional: false,
      type: 'string',
    },
  },
  name: 'regionInvitations',
  primaryKey: ['id'],
  serverName: 'region_invitations',
} as const
const regionMembersTable = {
  columns: {
    authUserFk: {
      customType: null as unknown as string,
      optional: false,
      serverName: 'auth_user_fk',
      type: 'string',
    },
    createdAt: {
      customType: null as unknown as number,
      optional: true,
      serverName: 'created_at',
      type: 'number',
    },
    id: {
      customType: null as unknown as number,
      optional: false,
      type: 'number',
    },
    invitedByFk: {
      customType: null as unknown as number,
      optional: true,
      serverName: 'invited_by',
      type: 'number',
    },
    isActive: {
      customType: null as unknown as boolean,
      optional: true,
      serverName: 'is_active',
      type: 'boolean',
    },
    regionFk: {
      customType: null as unknown as number,
      optional: false,
      serverName: 'region_fk',
      type: 'number',
    },
    role: {
      customType: null as unknown as 'app_admin' | 'region_admin' | 'region_maintainer' | 'region_user',
      optional: false,
      type: 'string',
    },
    userFk: {
      customType: null as unknown as number,
      optional: false,
      serverName: 'user_fk',
      type: 'number',
    },
  },
  name: 'regionMembers',
  primaryKey: ['id'],
  serverName: 'region_members',
} as const
const regionsTable = {
  columns: {
    createdAt: {
      customType: null as unknown as number,
      optional: true,
      serverName: 'created_at',
      type: 'number',
    },
    createdBy: {
      customType: null as unknown as number,
      optional: false,
      serverName: 'created_by',
      type: 'number',
    },
    id: {
      customType: null as unknown as number,
      optional: false,
      type: 'number',
    },
    maxMembers: {
      customType: null as unknown as number,
      optional: true,
      serverName: 'max_members',
      type: 'number',
    },
    name: {
      customType: null as unknown as string,
      optional: false,
      type: 'string',
    },
    settings: {
      customType: null as unknown as CustomType<typeof drizzleSchema, 'regions', 'settings'>,
      optional: true,
      type: 'json',
    },
  },
  name: 'regions',
  primaryKey: ['id'],
} as const
const rolePermissionsTable = {
  columns: {
    id: {
      customType: null as unknown as number,
      optional: false,
      type: 'number',
    },
    permission: {
      customType: null as unknown as CustomType<typeof drizzleSchema, 'rolePermissions', 'permission'>,
      optional: false,
      type: 'string',
    },
    role: {
      customType: null as unknown as 'app_admin' | 'region_admin' | 'region_maintainer' | 'region_user',
      optional: false,
      type: 'string',
    },
  },
  name: 'rolePermissions',
  primaryKey: ['id'],
  serverName: 'role_permissions',
} as const
const routeExternalResource27CragsTable = {
  columns: {
    country_name: {
      customType: null as unknown as string,
      optional: true,
      type: 'string',
    },
    crag_id: {
      customType: null as unknown as number,
      optional: true,
      type: 'number',
    },
    description: {
      customType: null as unknown as string,
      optional: true,
      type: 'string',
    },
    externalResourcesFk: {
      customType: null as unknown as number,
      optional: false,
      serverName: 'external_resources_fk',
      type: 'number',
    },
    id: {
      customType: null as unknown as number,
      optional: false,
      type: 'number',
    },
    latitude: {
      customType: null as unknown as number,
      optional: true,
      type: 'number',
    },
    location_name: {
      customType: null as unknown as string,
      optional: true,
      type: 'string',
    },
    longitude: {
      customType: null as unknown as number,
      optional: true,
      type: 'number',
    },
    name: {
      customType: null as unknown as string,
      optional: true,
      type: 'string',
    },
    path: {
      customType: null as unknown as string,
      optional: true,
      type: 'string',
    },
    regionFk: {
      customType: null as unknown as number,
      optional: false,
      serverName: 'region_fk',
      type: 'number',
    },
    searchable_id: {
      customType: null as unknown as number,
      optional: true,
      type: 'number',
    },
    searchable_type: {
      customType: null as unknown as string,
      optional: true,
      type: 'string',
    },
    url: {
      customType: null as unknown as string,
      optional: true,
      type: 'string',
    },
  },
  name: 'routeExternalResource27crags',
  primaryKey: ['id'],
  serverName: 'route_external_resource_27crags',
} as const
const routeExternalResource8ATable = {
  columns: {
    areaName: {
      customType: null as unknown as string,
      optional: true,
      serverName: 'area_name',
      type: 'string',
    },
    areaSlug: {
      customType: null as unknown as string,
      optional: true,
      serverName: 'area_slug',
      type: 'string',
    },
    averageRating: {
      customType: null as unknown as number,
      optional: true,
      serverName: 'average_rating',
      type: 'number',
    },
    category: {
      customType: null as unknown as number,
      optional: true,
      type: 'number',
    },
    countryName: {
      customType: null as unknown as string,
      optional: true,
      serverName: 'country_name',
      type: 'string',
    },
    countrySlug: {
      customType: null as unknown as string,
      optional: true,
      serverName: 'country_slug',
      type: 'string',
    },
    cragName: {
      customType: null as unknown as string,
      optional: true,
      serverName: 'crag_name',
      type: 'string',
    },
    cragSlug: {
      customType: null as unknown as string,
      optional: true,
      serverName: 'crag_slug',
      type: 'string',
    },
    difficulty: {
      customType: null as unknown as string,
      optional: true,
      type: 'string',
    },
    externalResourcesFk: {
      customType: null as unknown as number,
      optional: false,
      serverName: 'external_resources_fk',
      type: 'number',
    },
    gradeIndex: {
      customType: null as unknown as number,
      optional: true,
      serverName: 'grade_index',
      type: 'number',
    },
    id: {
      customType: null as unknown as number,
      optional: false,
      type: 'number',
    },
    regionFk: {
      customType: null as unknown as number,
      optional: false,
      serverName: 'region_fk',
      type: 'number',
    },
    sectorName: {
      customType: null as unknown as string,
      optional: true,
      serverName: 'sector_name',
      type: 'string',
    },
    sectorSlug: {
      customType: null as unknown as string,
      optional: true,
      serverName: 'sector_slug',
      type: 'string',
    },
    type: {
      customType: null as unknown as number,
      optional: true,
      type: 'number',
    },
    url: {
      customType: null as unknown as string,
      optional: true,
      type: 'string',
    },
    zlaggableId: {
      customType: null as unknown as number,
      optional: true,
      serverName: 'zlaggable_id',
      type: 'number',
    },
    zlaggableName: {
      customType: null as unknown as string,
      optional: true,
      serverName: 'zlaggable_name',
      type: 'string',
    },
    zlaggableSlug: {
      customType: null as unknown as string,
      optional: true,
      serverName: 'zlaggable_slug',
      type: 'string',
    },
  },
  name: 'routeExternalResource8a',
  primaryKey: ['id'],
  serverName: 'route_external_resource_8a',
} as const
const routeExternalResourceTheCragTable = {
  columns: {
    description: {
      customType: null as unknown as string,
      optional: true,
      type: 'string',
    },
    externalResourcesFk: {
      customType: null as unknown as number,
      optional: false,
      serverName: 'external_resources_fk',
      type: 'number',
    },
    grade: {
      customType: null as unknown as string,
      optional: true,
      type: 'string',
    },
    id: {
      customType: null as unknown as number,
      optional: false,
      type: 'number',
    },
    name: {
      customType: null as unknown as string,
      optional: true,
      type: 'string',
    },
    node: {
      customType: null as unknown as number,
      optional: true,
      type: 'number',
    },
    rating: {
      customType: null as unknown as number,
      optional: true,
      type: 'number',
    },
    regionFk: {
      customType: null as unknown as number,
      optional: false,
      serverName: 'region_fk',
      type: 'number',
    },
    tags: {
      customType: null as unknown as string,
      optional: true,
      type: 'string',
    },
    url: {
      customType: null as unknown as string,
      optional: true,
      type: 'string',
    },
  },
  name: 'routeExternalResourceTheCrag',
  primaryKey: ['id'],
  serverName: 'route_external_resource_the_crag',
} as const
const routeExternalResourcesTable = {
  columns: {
    externalResource8aFk: {
      customType: null as unknown as number,
      optional: true,
      serverName: 'external_resource_8a_fk',
      type: 'number',
    },
    externalResource27cragsFk: {
      customType: null as unknown as number,
      optional: true,
      serverName: 'external_resource_27crags_fk',
      type: 'number',
    },
    externalResourceTheCragFk: {
      customType: null as unknown as number,
      optional: true,
      serverName: 'external_resource_the_crag_fk',
      type: 'number',
    },
    id: {
      customType: null as unknown as number,
      optional: false,
      type: 'number',
    },
    regionFk: {
      customType: null as unknown as number,
      optional: false,
      serverName: 'region_fk',
      type: 'number',
    },
    routeFk: {
      customType: null as unknown as number,
      optional: false,
      serverName: 'route_fk',
      type: 'number',
    },
  },
  name: 'routeExternalResources',
  primaryKey: ['id'],
  serverName: 'route_external_resources',
} as const
const routesTable = {
  columns: {
    areaFks: {
      customType: null as unknown as number[],
      optional: true,
      serverName: 'area_fks',
      type: 'json',
    },
    areaIds: {
      customType: null as unknown as string,
      optional: true,
      serverName: 'area_ids',
      type: 'string',
    },
    blockFk: {
      customType: null as unknown as number,
      optional: false,
      serverName: 'block_fk',
      type: 'number',
    },
    createdAt: {
      customType: null as unknown as number,
      optional: true,
      serverName: 'created_at',
      type: 'number',
    },
    createdBy: {
      customType: null as unknown as number,
      optional: false,
      serverName: 'created_by',
      type: 'number',
    },
    deletedAt: {
      customType: null as unknown as number,
      optional: true,
      serverName: 'deleted_at',
      type: 'number',
    },
    description: {
      customType: null as unknown as string,
      optional: true,
      type: 'string',
    },
    externalResourcesFk: {
      customType: null as unknown as number,
      optional: true,
      serverName: 'external_resources_fk',
      type: 'number',
    },
    firstAscentYear: {
      customType: null as unknown as number,
      optional: true,
      serverName: 'first_ascent_year',
      type: 'number',
    },
    gradeFk: {
      customType: null as unknown as number,
      optional: true,
      serverName: 'grade_fk',
      type: 'number',
    },
    id: {
      customType: null as unknown as number,
      optional: false,
      type: 'number',
    },
    name: {
      customType: null as unknown as string,
      optional: false,
      type: 'string',
    },
    rating: {
      customType: null as unknown as number,
      optional: true,
      type: 'number',
    },
    regionFk: {
      customType: null as unknown as number,
      optional: false,
      serverName: 'region_fk',
      type: 'number',
    },
    userGradeFk: {
      customType: null as unknown as number,
      optional: true,
      serverName: 'user_grade_fk',
      type: 'number',
    },
    userRating: {
      customType: null as unknown as number,
      optional: true,
      serverName: 'user_rating',
      type: 'number',
    },
  },
  name: 'routes',
  primaryKey: ['id'],
} as const
const routesToFirstAscensionistsTable = {
  columns: {
    firstAscensionistFk: {
      customType: null as unknown as number,
      optional: false,
      serverName: 'first_ascensionist_fk',
      type: 'number',
    },
    id: {
      customType: null as unknown as number,
      optional: false,
      type: 'number',
    },
    regionFk: {
      customType: null as unknown as number,
      optional: false,
      serverName: 'region_fk',
      type: 'number',
    },
    routeFk: {
      customType: null as unknown as number,
      optional: false,
      serverName: 'route_fk',
      type: 'number',
    },
  },
  name: 'routesToFirstAscensionists',
  primaryKey: ['id'],
  serverName: 'routes_to_first_ascensionists',
} as const
const routesToTagsTable = {
  columns: {
    regionFk: {
      customType: null as unknown as number,
      optional: false,
      serverName: 'region_fk',
      type: 'number',
    },
    routeFk: {
      customType: null as unknown as number,
      optional: false,
      serverName: 'route_fk',
      type: 'number',
    },
    tagFk: {
      customType: null as unknown as string,
      optional: false,
      serverName: 'tag_fk',
      type: 'string',
    },
  },
  name: 'routesToTags',
  primaryKey: ['routeFk', 'tagFk'],
  serverName: 'routes_to_tags',
} as const
const topoRoutesTable = {
  columns: {
    id: {
      customType: null as unknown as number,
      optional: false,
      type: 'number',
    },
    path: {
      customType: null as unknown as string,
      optional: true,
      type: 'string',
    },
    regionFk: {
      customType: null as unknown as number,
      optional: false,
      serverName: 'region_fk',
      type: 'number',
    },
    routeFk: {
      customType: null as unknown as number,
      optional: true,
      serverName: 'route_fk',
      type: 'number',
    },
    topoFk: {
      customType: null as unknown as number,
      optional: true,
      serverName: 'topo_fk',
      type: 'number',
    },
    topType: {
      customType: null as unknown as 'top' | 'topout',
      optional: false,
      serverName: 'top_type',
      type: 'string',
    },
  },
  name: 'topoRoutes',
  primaryKey: ['id'],
  serverName: 'topo_routes',
} as const
const toposTable = {
  columns: {
    blockFk: {
      customType: null as unknown as number,
      optional: true,
      serverName: 'block_fk',
      type: 'number',
    },
    fileFk: {
      customType: null as unknown as string,
      optional: true,
      serverName: 'file_fk',
      type: 'string',
    },
    id: {
      customType: null as unknown as number,
      optional: false,
      type: 'number',
    },
    order: {
      customType: null as unknown as number,
      optional: true,
      type: 'number',
    },
    regionFk: {
      customType: null as unknown as number,
      optional: false,
      serverName: 'region_fk',
      type: 'number',
    },
  },
  name: 'topos',
  primaryKey: ['id'],
} as const
const userRolesTable = {
  columns: {
    authUserFk: {
      customType: null as unknown as string,
      optional: false,
      serverName: 'auth_user_fk',
      type: 'string',
    },
    id: {
      customType: null as unknown as number,
      optional: false,
      type: 'number',
    },
    role: {
      customType: null as unknown as 'app_admin' | 'region_admin' | 'region_maintainer' | 'region_user',
      optional: false,
      type: 'string',
    },
  },
  name: 'userRoles',
  primaryKey: ['id'],
  serverName: 'user_roles',
} as const
const userSettingsTable = {
  columns: {
    authUserFk: {
      customType: null as unknown as string,
      optional: false,
      serverName: 'auth_user_fk',
      type: 'string',
    },
    contactLocale: {
      customType: null as unknown as string,
      optional: true,
      serverName: 'contact_locale',
      type: 'string',
    },
    cookie8a: {
      customType: null as unknown as string,
      optional: true,
      serverName: 'cookie_8a',
      type: 'string',
    },
    cookie27crags: {
      customType: null as unknown as string,
      optional: true,
      serverName: 'cookie_27crags',
      type: 'string',
    },
    cookieTheCrag: {
      customType: null as unknown as string,
      optional: true,
      serverName: 'cookie_the_crag',
      type: 'string',
    },
    gradingScale: {
      customType: null as unknown as 'FB' | 'V',
      optional: true,
      serverName: 'grading_scale',
      type: 'string',
    },
    id: {
      customType: null as unknown as number,
      optional: false,
      type: 'number',
    },
    notifyModerations: {
      customType: null as unknown as boolean,
      optional: true,
      serverName: 'notify_moderations',
      type: 'boolean',
    },
    notifyNewAscents: {
      customType: null as unknown as boolean,
      optional: true,
      serverName: 'notify_new_ascents',
      type: 'boolean',
    },
    notifyNewUsers: {
      customType: null as unknown as boolean,
      optional: true,
      serverName: 'notify_new_users',
      type: 'boolean',
    },
    unitSystem: {
      customType: null as unknown as 'imperial' | 'metric',
      optional: true,
      serverName: 'unit_system',
      type: 'string',
    },
    userFk: {
      customType: null as unknown as number,
      optional: false,
      serverName: 'user_fk',
      type: 'number',
    },
  },
  name: 'userSettings',
  primaryKey: ['id'],
  serverName: 'user_settings',
} as const
const usersTable = {
  columns: {
    authUserFk: {
      customType: null as unknown as string,
      optional: false,
      serverName: 'auth_user_fk',
      type: 'string',
    },
    createdAt: {
      customType: null as unknown as number,
      optional: true,
      serverName: 'created_at',
      type: 'number',
    },
    firstAscensionistFk: {
      customType: null as unknown as number,
      optional: true,
      serverName: 'first_ascentionist_fk',
      type: 'number',
    },
    id: {
      customType: null as unknown as number,
      optional: false,
      type: 'number',
    },
    username: {
      customType: null as unknown as string,
      optional: false,
      type: 'string',
    },
    userSettingsFk: {
      customType: null as unknown as number,
      optional: true,
      serverName: 'user_settings_fk',
      type: 'number',
    },
  },
  name: 'users',
  primaryKey: ['id'],
} as const
const activitiesRelationships = {
  region: [{ cardinality: 'one', destField: ['id'], destSchema: 'regions', sourceField: ['regionFk'] }],
  user: [{ cardinality: 'one', destField: ['id'], destSchema: 'users', sourceField: ['userFk'] }],
} as const
const areasRelationships = {
  areas: [{ cardinality: 'many', destField: ['parentFk'], destSchema: 'areas', sourceField: ['id'] }],
  author: [{ cardinality: 'one', destField: ['id'], destSchema: 'users', sourceField: ['createdBy'] }],
  blocks: [{ cardinality: 'many', destField: ['areaFk'], destSchema: 'blocks', sourceField: ['id'] }],
  files: [{ cardinality: 'many', destField: ['areaFk'], destSchema: 'files', sourceField: ['id'] }],
  parent: [{ cardinality: 'one', destField: ['id'], destSchema: 'areas', sourceField: ['parentFk'] }],
  parkingLocations: [{ cardinality: 'many', destField: ['areaFk'], destSchema: 'geolocations', sourceField: ['id'] }],
  region: [{ cardinality: 'one', destField: ['id'], destSchema: 'regions', sourceField: ['regionFk'] }],
} as const
const ascentsRelationships = {
  author: [{ cardinality: 'one', destField: ['id'], destSchema: 'users', sourceField: ['createdBy'] }],
  files: [{ cardinality: 'many', destField: ['ascentFk'], destSchema: 'files', sourceField: ['id'] }],
  grade: [{ cardinality: 'one', destField: ['id'], destSchema: 'grades', sourceField: ['gradeFk'] }],
  region: [{ cardinality: 'one', destField: ['id'], destSchema: 'regions', sourceField: ['regionFk'] }],
  route: [{ cardinality: 'one', destField: ['id'], destSchema: 'routes', sourceField: ['routeFk'] }],
} as const
const blocksRelationships = {
  area: [{ cardinality: 'one', destField: ['id'], destSchema: 'areas', sourceField: ['areaFk'] }],
  author: [{ cardinality: 'one', destField: ['id'], destSchema: 'users', sourceField: ['createdBy'] }],
  files: [{ cardinality: 'many', destField: ['blockFk'], destSchema: 'files', sourceField: ['id'] }],
  geolocation: [{ cardinality: 'one', destField: ['id'], destSchema: 'geolocations', sourceField: ['geolocationFk'] }],
  region: [{ cardinality: 'one', destField: ['id'], destSchema: 'regions', sourceField: ['regionFk'] }],
  routes: [{ cardinality: 'many', destField: ['blockFk'], destSchema: 'routes', sourceField: ['id'] }],
  topos: [{ cardinality: 'many', destField: ['blockFk'], destSchema: 'topos', sourceField: ['id'] }],
} as const
const bunnyStreamsRelationships = {
  file: [{ cardinality: 'one', destField: ['id'], destSchema: 'files', sourceField: ['fileFk'] }],
  region: [{ cardinality: 'one', destField: ['id'], destSchema: 'regions', sourceField: ['regionFk'] }],
} as const
const favoritesRelationships = {
  authUser: [{ cardinality: 'one', destField: ['id'], destSchema: 'users', sourceField: ['authUserFk'] }],
  region: [{ cardinality: 'one', destField: ['id'], destSchema: 'regions', sourceField: ['regionFk'] }],
  user: [{ cardinality: 'one', destField: ['id'], destSchema: 'users', sourceField: ['userFk'] }],
} as const
const filesRelationships = {
  area: [{ cardinality: 'one', destField: ['id'], destSchema: 'areas', sourceField: ['areaFk'] }],
  ascent: [{ cardinality: 'one', destField: ['id'], destSchema: 'ascents', sourceField: ['ascentFk'] }],
  author: [{ cardinality: 'one', destField: ['id'], destSchema: 'users', sourceField: ['createdBy'] }],
  block: [{ cardinality: 'one', destField: ['id'], destSchema: 'blocks', sourceField: ['blockFk'] }],
  bunnyStream: [{ cardinality: 'one', destField: ['id'], destSchema: 'bunnyStreams', sourceField: ['bunnyStreamFk'] }],
  region: [{ cardinality: 'one', destField: ['id'], destSchema: 'regions', sourceField: ['regionFk'] }],
  route: [{ cardinality: 'one', destField: ['id'], destSchema: 'routes', sourceField: ['routeFk'] }],
} as const
const firstAscensionistsRelationships = {
  region: [{ cardinality: 'one', destField: ['id'], destSchema: 'regions', sourceField: ['regionFk'] }],
  routes: [
    {
      cardinality: 'many',
      destField: ['firstAscensionistFk'],
      destSchema: 'routesToFirstAscensionists',
      sourceField: ['id'],
    },
  ],
  user: [{ cardinality: 'one', destField: ['id'], destSchema: 'users', sourceField: ['userFk'] }],
} as const
const geolocationsRelationships = {
  area: [{ cardinality: 'one', destField: ['id'], destSchema: 'areas', sourceField: ['areaFk'] }],
  block: [{ cardinality: 'one', destField: ['id'], destSchema: 'blocks', sourceField: ['blockFk'] }],
  region: [{ cardinality: 'one', destField: ['id'], destSchema: 'regions', sourceField: ['regionFk'] }],
} as const
const gradesRelationships = {
  ascents: [{ cardinality: 'many', destField: ['gradeFk'], destSchema: 'ascents', sourceField: ['id'] }],
  routes: [{ cardinality: 'many', destField: ['gradeFk'], destSchema: 'routes', sourceField: ['id'] }],
} as const
const pushSubscriptionsRelationships = {
  authUser: [{ cardinality: 'one', destField: ['id'], destSchema: 'users', sourceField: ['authUserFk'] }],
  user: [{ cardinality: 'one', destField: ['id'], destSchema: 'users', sourceField: ['userFk'] }],
} as const
const regionInvitationsRelationships = {
  acceptedBy: [{ cardinality: 'one', destField: ['id'], destSchema: 'users', sourceField: ['acceptedByFk'] }],
  invitedBy: [{ cardinality: 'one', destField: ['id'], destSchema: 'users', sourceField: ['invitedByFk'] }],
  region: [{ cardinality: 'one', destField: ['id'], destSchema: 'regions', sourceField: ['regionFk'] }],
} as const
const regionMembersRelationships = {
  authUser: [{ cardinality: 'one', destField: ['id'], destSchema: 'users', sourceField: ['authUserFk'] }],
  invitedBy: [{ cardinality: 'one', destField: ['id'], destSchema: 'users', sourceField: ['invitedByFk'] }],
  region: [{ cardinality: 'one', destField: ['id'], destSchema: 'regions', sourceField: ['regionFk'] }],
  rolePermission: [{ cardinality: 'one', destField: ['role'], destSchema: 'rolePermissions', sourceField: ['role'] }],
  user: [{ cardinality: 'one', destField: ['id'], destSchema: 'users', sourceField: ['userFk'] }],
} as const
const regionsRelationships = {
  author: [{ cardinality: 'one', destField: ['id'], destSchema: 'users', sourceField: ['createdBy'] }],
  members: [{ cardinality: 'many', destField: ['regionFk'], destSchema: 'regionMembers', sourceField: ['id'] }],
} as const
const rolePermissionsRelationships = {
  regionMembers: [{ cardinality: 'many', destField: ['role'], destSchema: 'regionMembers', sourceField: ['role'] }],
} as const
const routeExternalResource27CragsRelationships = {
  externalResources: [
    {
      cardinality: 'one',
      destField: ['id'],
      destSchema: 'routeExternalResources',
      sourceField: ['externalResourcesFk'],
    },
  ],
  region: [{ cardinality: 'one', destField: ['id'], destSchema: 'regions', sourceField: ['regionFk'] }],
} as const
const routeExternalResource8ARelationships = {
  externalResources: [
    {
      cardinality: 'one',
      destField: ['id'],
      destSchema: 'routeExternalResources',
      sourceField: ['externalResourcesFk'],
    },
  ],
  region: [{ cardinality: 'one', destField: ['id'], destSchema: 'regions', sourceField: ['regionFk'] }],
} as const
const routeExternalResourceTheCragRelationships = {
  externalResources: [
    {
      cardinality: 'one',
      destField: ['id'],
      destSchema: 'routeExternalResources',
      sourceField: ['externalResourcesFk'],
    },
  ],
  region: [{ cardinality: 'one', destField: ['id'], destSchema: 'regions', sourceField: ['regionFk'] }],
} as const
const routeExternalResourcesRelationships = {
  externalResource8a: [
    {
      cardinality: 'one',
      destField: ['id'],
      destSchema: 'routeExternalResource8a',
      sourceField: ['externalResource8aFk'],
    },
  ],
  externalResource27crags: [
    {
      cardinality: 'one',
      destField: ['id'],
      destSchema: 'routeExternalResource27crags',
      sourceField: ['externalResource27cragsFk'],
    },
  ],
  externalResourceTheCrag: [
    {
      cardinality: 'one',
      destField: ['id'],
      destSchema: 'routeExternalResourceTheCrag',
      sourceField: ['externalResourceTheCragFk'],
    },
  ],
  region: [{ cardinality: 'one', destField: ['id'], destSchema: 'regions', sourceField: ['regionFk'] }],
  route: [{ cardinality: 'one', destField: ['id'], destSchema: 'routes', sourceField: ['routeFk'] }],
} as const
const routesRelationships = {
  ascents: [{ cardinality: 'many', destField: ['routeFk'], destSchema: 'ascents', sourceField: ['id'] }],
  author: [{ cardinality: 'one', destField: ['id'], destSchema: 'users', sourceField: ['createdBy'] }],
  block: [{ cardinality: 'one', destField: ['id'], destSchema: 'blocks', sourceField: ['blockFk'] }],
  externalResources: [
    {
      cardinality: 'one',
      destField: ['id'],
      destSchema: 'routeExternalResources',
      sourceField: ['externalResourcesFk'],
    },
  ],
  files: [{ cardinality: 'many', destField: ['routeFk'], destSchema: 'files', sourceField: ['id'] }],
  firstAscents: [
    { cardinality: 'many', destField: ['routeFk'], destSchema: 'routesToFirstAscensionists', sourceField: ['id'] },
  ],
  grade: [{ cardinality: 'one', destField: ['id'], destSchema: 'grades', sourceField: ['gradeFk'] }],
  region: [{ cardinality: 'one', destField: ['id'], destSchema: 'regions', sourceField: ['regionFk'] }],
  tags: [{ cardinality: 'many', destField: ['routeFk'], destSchema: 'routesToTags', sourceField: ['id'] }],
  topoRoutes: [{ cardinality: 'many', destField: ['routeFk'], destSchema: 'topoRoutes', sourceField: ['id'] }],
} as const
const routesToFirstAscensionistsRelationships = {
  firstAscensionist: [
    { cardinality: 'one', destField: ['id'], destSchema: 'firstAscensionists', sourceField: ['firstAscensionistFk'] },
  ],
  region: [{ cardinality: 'one', destField: ['id'], destSchema: 'regions', sourceField: ['regionFk'] }],
  route: [{ cardinality: 'one', destField: ['id'], destSchema: 'routes', sourceField: ['routeFk'] }],
} as const
const routesToTagsRelationships = {
  region: [{ cardinality: 'one', destField: ['id'], destSchema: 'regions', sourceField: ['regionFk'] }],
  route: [{ cardinality: 'one', destField: ['id'], destSchema: 'routes', sourceField: ['routeFk'] }],
} as const
const topoRoutesRelationships = {
  region: [{ cardinality: 'one', destField: ['id'], destSchema: 'regions', sourceField: ['regionFk'] }],
  route: [{ cardinality: 'one', destField: ['id'], destSchema: 'routes', sourceField: ['routeFk'] }],
  topo: [{ cardinality: 'one', destField: ['id'], destSchema: 'topos', sourceField: ['topoFk'] }],
} as const
const toposRelationships = {
  block: [{ cardinality: 'one', destField: ['id'], destSchema: 'blocks', sourceField: ['blockFk'] }],
  file: [{ cardinality: 'one', destField: ['id'], destSchema: 'files', sourceField: ['fileFk'] }],
  region: [{ cardinality: 'one', destField: ['id'], destSchema: 'regions', sourceField: ['regionFk'] }],
  routes: [{ cardinality: 'many', destField: ['topoFk'], destSchema: 'topoRoutes', sourceField: ['id'] }],
} as const
const userRolesRelationships = {
  rolePermission: [{ cardinality: 'one', destField: ['role'], destSchema: 'rolePermissions', sourceField: ['role'] }],
} as const
const userSettingsRelationships = {
  authUser: [{ cardinality: 'one', destField: ['id'], destSchema: 'users', sourceField: ['authUserFk'] }],
  user: [{ cardinality: 'one', destField: ['id'], destSchema: 'users', sourceField: ['userFk'] }],
} as const
const usersRelationships = {
  areas: [{ cardinality: 'many', destField: ['createdBy'], destSchema: 'areas', sourceField: ['id'] }],
  ascents: [{ cardinality: 'many', destField: ['createdBy'], destSchema: 'ascents', sourceField: ['id'] }],
  authUser: [{ cardinality: 'one', destField: ['id'], destSchema: 'users', sourceField: ['authUserFk'] }],
  blocks: [{ cardinality: 'many', destField: ['createdBy'], destSchema: 'blocks', sourceField: ['id'] }],
  favorites: [{ cardinality: 'many', destField: ['userFk'], destSchema: 'favorites', sourceField: ['id'] }],
  firstAscensionist: [
    { cardinality: 'one', destField: ['id'], destSchema: 'firstAscensionists', sourceField: ['firstAscensionistFk'] },
  ],
  pushSubscriptions: [
    { cardinality: 'many', destField: ['userFk'], destSchema: 'pushSubscriptions', sourceField: ['id'] },
  ],
  regionMemberships: [{ cardinality: 'many', destField: ['userFk'], destSchema: 'regionMembers', sourceField: ['id'] }],
  routes: [{ cardinality: 'many', destField: ['createdBy'], destSchema: 'routes', sourceField: ['id'] }],
  userSettings: [
    { cardinality: 'one', destField: ['id'], destSchema: 'userSettings', sourceField: ['userSettingsFk'] },
  ],
} as const
/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  enableLegacyMutators: false,
  enableLegacyQueries: false,
  relationships: {
    activities: activitiesRelationships,
    areas: areasRelationships,
    ascents: ascentsRelationships,
    blocks: blocksRelationships,
    bunnyStreams: bunnyStreamsRelationships,
    favorites: favoritesRelationships,
    files: filesRelationships,
    firstAscensionists: firstAscensionistsRelationships,
    geolocations: geolocationsRelationships,
    grades: gradesRelationships,
    pushSubscriptions: pushSubscriptionsRelationships,
    regionInvitations: regionInvitationsRelationships,
    regionMembers: regionMembersRelationships,
    regions: regionsRelationships,
    rolePermissions: rolePermissionsRelationships,
    routeExternalResource8a: routeExternalResource8ARelationships,
    routeExternalResource27crags: routeExternalResource27CragsRelationships,
    routeExternalResources: routeExternalResourcesRelationships,
    routeExternalResourceTheCrag: routeExternalResourceTheCragRelationships,
    routes: routesRelationships,
    routesToFirstAscensionists: routesToFirstAscensionistsRelationships,
    routesToTags: routesToTagsRelationships,
    topoRoutes: topoRoutesRelationships,
    topos: toposRelationships,
    userRoles: userRolesRelationships,
    users: usersRelationships,
    userSettings: userSettingsRelationships,
  },
  tables: {
    activities: activitiesTable,
    areas: areasTable,
    ascents: ascentsTable,
    blocks: blocksTable,
    bunnyStreams: bunnyStreamsTable,
    clientErrorLogs: clientErrorLogsTable,
    favorites: favoritesTable,
    files: filesTable,
    firstAscensionists: firstAscensionistsTable,
    geolocations: geolocationsTable,
    grades: gradesTable,
    pushSubscriptions: pushSubscriptionsTable,
    regionInvitations: regionInvitationsTable,
    regionMembers: regionMembersTable,
    regions: regionsTable,
    rolePermissions: rolePermissionsTable,
    routeExternalResource8a: routeExternalResource8ATable,
    routeExternalResource27crags: routeExternalResource27CragsTable,
    routeExternalResources: routeExternalResourcesTable,
    routeExternalResourceTheCrag: routeExternalResourceTheCragTable,
    routes: routesTable,
    routesToFirstAscensionists: routesToFirstAscensionistsTable,
    routesToTags: routesToTagsTable,
    topoRoutes: topoRoutesTable,
    topos: toposTable,
    userRoles: userRolesTable,
    users: usersTable,
    userSettings: userSettingsTable,
  },
} as const

/**
 * Represents a row from the "activities" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Activity = Row<(typeof schema)['tables']['activities']>
/**
 * Represents a row from the "areas" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Area = Row<(typeof schema)['tables']['areas']>
/**
 * Represents a row from the "ascents" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Ascent = Row<(typeof schema)['tables']['ascents']>
/**
 * Represents a row from the "blocks" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Block = Row<(typeof schema)['tables']['blocks']>
/**
 * Represents a row from the "bunnyStreams" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type BunnyStream = Row<(typeof schema)['tables']['bunnyStreams']>
/**
 * Represents a row from the "clientErrorLogs" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ClientErrorLog = Row<(typeof schema)['tables']['clientErrorLogs']>
/**
 * Represents a row from the "favorites" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Favorite = Row<(typeof schema)['tables']['favorites']>
/**
 * Represents a row from the "files" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type File = Row<(typeof schema)['tables']['files']>
/**
 * Represents a row from the "firstAscensionists" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type FirstAscensionist = Row<(typeof schema)['tables']['firstAscensionists']>
/**
 * Represents a row from the "geolocations" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Geolocation = Row<(typeof schema)['tables']['geolocations']>
/**
 * Represents a row from the "grades" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Grade = Row<(typeof schema)['tables']['grades']>
/**
 * Represents a row from the "pushSubscriptions" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type PushSubscription = Row<(typeof schema)['tables']['pushSubscriptions']>
/**
 * Represents a row from the "regions" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Region = Row<(typeof schema)['tables']['regions']>
/**
 * Represents a row from the "regionInvitations" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type RegionInvitation = Row<(typeof schema)['tables']['regionInvitations']>
/**
 * Represents a row from the "regionMembers" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type RegionMember = Row<(typeof schema)['tables']['regionMembers']>
/**
 * Represents a row from the "rolePermissions" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type RolePermission = Row<(typeof schema)['tables']['rolePermissions']>
/**
 * Represents a row from the "routes" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Route = Row<(typeof schema)['tables']['routes']>
/**
 * Represents a row from the "routeExternalResources" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type RouteExternalResource = Row<(typeof schema)['tables']['routeExternalResources']>
/**
 * Represents a row from the "routeExternalResource8a" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type RouteExternalResource8A = Row<(typeof schema)['tables']['routeExternalResource8a']>
/**
 * Represents a row from the "routeExternalResource27crags" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type RouteExternalResource27Crag = Row<(typeof schema)['tables']['routeExternalResource27crags']>
/**
 * Represents a row from the "routeExternalResourceTheCrag" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type RouteExternalResourceTheCrag = Row<(typeof schema)['tables']['routeExternalResourceTheCrag']>
/**
 * Represents a row from the "routesToFirstAscensionists" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type RoutesToFirstAscensionist = Row<(typeof schema)['tables']['routesToFirstAscensionists']>
/**
 * Represents a row from the "routesToTags" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type RoutesToTag = Row<(typeof schema)['tables']['routesToTags']>
/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema
/**
 * Represents a row from the "topos" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Topo = Row<(typeof schema)['tables']['topos']>
/**
 * Represents a row from the "topoRoutes" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type TopoRoute = Row<(typeof schema)['tables']['topoRoutes']>
/**
 * Represents a row from the "users" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type User = Row<(typeof schema)['tables']['users']>
/**
 * Represents a row from the "userRoles" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type UserRole = Row<(typeof schema)['tables']['userRoles']>
/**
 * Represents a row from the "userSettings" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type UserSetting = Row<(typeof schema)['tables']['userSettings']>

/**
 * Represents the ZQL query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const zql = createBuilder(schema)
/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const builder = zql

/** Defines the default types for Zero */
declare module '@rocicorp/zero' {
  interface DefaultTypes {
    schema: Schema
  }
}
