// @generated drizzle-zero signature:sha256:dcb5c0acac99f3c696c0ace8499d607cd61dc02e5e3bcec9b1d84ab0bacd4382
// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.

import type { Row } from '@rocicorp/zero'
import { createBuilder } from '@rocicorp/zero'
import type { CustomType } from 'drizzle-zero'
import type * as drizzleSchema from '../db/schema'

const activitiesTable = {
  name: 'activities',
  columns: {
    createdAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'created_at',
    },
    id: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    regionFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'region_fk',
    },
    columnName: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'column_name',
    },
    entityId: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'entity_id',
    },
    entityType: {
      type: 'string',
      optional: false,
      customType: null as unknown as 'block' | 'route' | 'area' | 'ascent' | 'file' | 'user',
      serverName: 'entity_type',
    },
    metadata: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    newValue: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'new_value',
    },
    oldValue: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'old_value',
    },
    parentEntityId: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'parent_entity_id',
    },
    parentEntityType: {
      type: 'string',
      optional: true,
      customType: null as unknown as 'block' | 'route' | 'area' | 'ascent',
      serverName: 'parent_entity_type',
    },
    type: {
      type: 'string',
      optional: false,
      customType: null as unknown as 'created' | 'updated' | 'deleted' | 'uploaded',
    },
    userFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'user_fk',
    },
  },
  primaryKey: ['id'],
} as const
const areasTable = {
  name: 'areas',
  columns: {
    createdAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'created_at',
    },
    id: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    createdBy: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'created_by',
    },
    name: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    regionFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'region_fk',
    },
    deletedAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'deleted_at',
    },
    description: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    geoPaths: {
      type: 'json',
      optional: true,
      customType: null as unknown as string[],
      serverName: 'geo_paths',
    },
    parentFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'parent_fk',
    },
    type: {
      type: 'string',
      optional: true,
      customType: null as unknown as 'area' | 'crag',
    },
    walkingPaths: {
      type: 'json',
      optional: true,
      customType: null as unknown as string[],
      serverName: 'walking_paths',
    },
  },
  primaryKey: ['id'],
} as const
const ascentsTable = {
  name: 'ascents',
  columns: {
    createdAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'created_at',
    },
    id: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    regionFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'region_fk',
    },
    deletedAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'deleted_at',
    },
    accolade: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    createdBy: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'created_by',
    },
    dateTime: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'date_time',
    },
    gradeFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'grade_fk',
    },
    humidity: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
    },
    notes: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    rating: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
    },
    routeFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'route_fk',
    },
    temperature: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
    },
    type: {
      type: 'string',
      optional: false,
      customType: null as unknown as 'repeat' | 'flash' | 'redpoint' | 'attempt',
    },
  },
  primaryKey: ['id'],
} as const
const blocksTable = {
  name: 'blocks',
  columns: {
    createdAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'created_at',
    },
    id: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    createdBy: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'created_by',
    },
    name: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    regionFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'region_fk',
    },
    deletedAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'deleted_at',
    },
    areaFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'area_fk',
    },
    description: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    geolocationFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'geolocation_fk',
    },
    order: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
  },
  primaryKey: ['id'],
} as const
const bunnyStreamsTable = {
  name: 'bunnyStreams',
  columns: {
    id: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    regionFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'region_fk',
    },
    fileFk: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'file_fk',
    },
    source: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
  },
  primaryKey: ['id'],
  serverName: 'bunny_streams',
} as const
const changesTable = {
  name: 'changes',
  columns: {
    createdAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'created_at',
    },
    id: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    regionFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'region_fk',
    },
    areaFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'area_fk',
    },
    ascentFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'ascent_fk',
    },
    blockFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'block_fk',
    },
    fileFk: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'file_fk',
    },
    routeFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'route_fk',
    },
    subjectFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'subject_fk',
    },
    columnName: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'column_name',
    },
    eventFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'event_fk',
    },
    newValue: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'new_value',
    },
    oldValue: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'old_value',
    },
  },
  primaryKey: ['id'],
} as const
const clientErrorLogsTable = {
  name: 'clientErrorLogs',
  columns: {
    createdAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'created_at',
    },
    id: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    createdBy: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'created_by',
    },
    error: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    navigator: {
      type: 'json',
      optional: true,
      customType: null as unknown as CustomType<typeof drizzleSchema, 'clientErrorLogs', 'navigator'>,
    },
    pathname: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    source: {
      type: 'string',
      optional: true,
      customType: null as unknown as 'client' | 'server',
    },
  },
  primaryKey: ['id'],
  serverName: 'client_error_logs',
} as const
const eventsTable = {
  name: 'events',
  columns: {
    createdAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'created_at',
    },
    id: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    regionFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'region_fk',
    },
    areaFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'area_fk',
    },
    ascentFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'ascent_fk',
    },
    blockFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'block_fk',
    },
    fileFk: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'file_fk',
    },
    routeFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'route_fk',
    },
    subjectFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'subject_fk',
    },
    actorFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'actor_fk',
    },
    commentCount: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'comment_count',
    },
    metadata: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    promoted: {
      type: 'boolean',
      optional: true,
      customType: null as unknown as boolean,
    },
    verb: {
      type: 'string',
      optional: false,
      customType: null as unknown as
        | 'update'
        | 'delete'
        | 'create'
        | 'add'
        | 'remove'
        | 'join'
        | 'leave'
        | 'invite'
        | 'accept',
    },
  },
  primaryKey: ['id'],
} as const
const favoritesTable = {
  name: 'favorites',
  columns: {
    createdAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'created_at',
    },
    id: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    regionFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'region_fk',
    },
    areaFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'area_fk',
    },
    authUserFk: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'auth_user_fk',
    },
    blockFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'block_fk',
    },
    routeFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'route_fk',
    },
    userFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'user_fk',
    },
  },
  primaryKey: ['id'],
} as const
const filesTable = {
  name: 'files',
  columns: {
    id: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    regionFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'region_fk',
    },
    areaFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'area_fk',
    },
    ascentFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'ascent_fk',
    },
    blockFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'block_fk',
    },
    bunnyStreamFk: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'bunny_stream_fk',
    },
    createdAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'created_at',
    },
    createdBy: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'created_by',
    },
    height: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
    },
    path: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    routeFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'route_fk',
    },
    visibility: {
      type: 'string',
      optional: true,
      customType: null as unknown as 'public' | 'private',
    },
    width: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
    },
  },
  primaryKey: ['id'],
} as const
const firstAscensionistsTable = {
  name: 'firstAscensionists',
  columns: {
    id: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    regionFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'region_fk',
    },
    name: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    userFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'user_fk',
    },
  },
  primaryKey: ['id'],
  serverName: 'first_ascensionists',
} as const
const geolocationsTable = {
  name: 'geolocations',
  columns: {
    id: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    regionFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'region_fk',
    },
    areaFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'area_fk',
    },
    blockFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'block_fk',
    },
    estimated: {
      type: 'boolean',
      optional: true,
      customType: null as unknown as boolean,
    },
    lat: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    long: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
  },
  primaryKey: ['id'],
} as const
const gradesTable = {
  name: 'grades',
  columns: {
    FB: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    id: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    V: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
  },
  primaryKey: ['id'],
} as const
const notificationsTable = {
  name: 'notifications',
  columns: {
    createdAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'created_at',
    },
    id: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    regionFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'region_fk',
    },
    actorFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'actor_fk',
    },
    authUserFk: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'auth_user_fk',
    },
    areaFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'area_fk',
    },
    ascentFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'ascent_fk',
    },
    blockFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'block_fk',
    },
    fileFk: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'file_fk',
    },
    routeFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'route_fk',
    },
    subjectFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'subject_fk',
    },
    eventFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'event_fk',
    },
    metadata: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    pushedAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'pushed_at',
    },
    reactionFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'reaction_fk',
    },
    readAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'read_at',
    },
    sourceType: {
      type: 'string',
      optional: false,
      customType: null as unknown as
        | 'mention'
        | 'ascent_edited'
        | 'ascent_deleted'
        | 'role_changed'
        | 'invite_accepted'
        | 'membership_removed'
        | 'invitation_received'
        | 'reaction'
        | 'comment'
        | 'comment_reply'
        | 'comment_reaction',
      serverName: 'source_type',
    },
    userFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'user_fk',
    },
  },
  primaryKey: ['id'],
} as const
const pushSubscriptionsTable = {
  name: 'pushSubscriptions',
  columns: {
    createdAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'created_at',
    },
    id: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    auth: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    authUserFk: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'auth_user_fk',
    },
    endpoint: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    expirationTime: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'expiration_time',
    },
    p256dh: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    userFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'user_fk',
    },
  },
  primaryKey: ['id'],
  serverName: 'push_subscriptions',
} as const
const reactionsTable = {
  name: 'reactions',
  columns: {
    createdAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'created_at',
    },
    id: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    regionFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'region_fk',
    },
    deletedAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'deleted_at',
    },
    authUserFk: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'auth_user_fk',
    },
    body: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    eventFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'event_fk',
    },
    parentFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'parent_fk',
    },
    type: {
      type: 'string',
      optional: false,
      customType: null as unknown as 'comment' | 'emoji',
    },
    updatedAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'updated_at',
    },
    userFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'user_fk',
    },
  },
  primaryKey: ['id'],
} as const
const regionInvitationsTable = {
  name: 'regionInvitations',
  columns: {
    createdAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'created_at',
    },
    id: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    regionFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'region_fk',
    },
    acceptedAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'accepted_at',
    },
    acceptedByFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'accepted_by',
    },
    email: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    expiresAt: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'expires_at',
    },
    invitedByFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'invited_by',
    },
    lastSentAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'last_sent_at',
    },
    status: {
      type: 'string',
      optional: true,
      customType: null as unknown as 'pending' | 'accepted' | 'expired',
    },
    token: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
  },
  primaryKey: ['id'],
  serverName: 'region_invitations',
} as const
const regionMembersTable = {
  name: 'regionMembers',
  columns: {
    createdAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'created_at',
    },
    id: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    regionFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'region_fk',
    },
    authUserFk: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'auth_user_fk',
    },
    invitedByFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'invited_by',
    },
    isActive: {
      type: 'boolean',
      optional: true,
      customType: null as unknown as boolean,
      serverName: 'is_active',
    },
    role: {
      type: 'string',
      optional: false,
      customType: null as unknown as 'app_admin' | 'region_user' | 'region_maintainer' | 'region_admin',
    },
    userFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'user_fk',
    },
  },
  primaryKey: ['id'],
  serverName: 'region_members',
} as const
const regionsTable = {
  name: 'regions',
  columns: {
    createdAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'created_at',
    },
    id: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    createdBy: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'created_by',
    },
    maxMembers: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'max_members',
    },
    name: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    settings: {
      type: 'json',
      optional: true,
      customType: null as unknown as CustomType<typeof drizzleSchema, 'regions', 'settings'>,
    },
  },
  primaryKey: ['id'],
} as const
const rolePermissionsTable = {
  name: 'rolePermissions',
  columns: {
    id: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    permission: {
      type: 'string',
      optional: false,
      customType: null as unknown as CustomType<typeof drizzleSchema, 'rolePermissions', 'permission'>,
    },
    role: {
      type: 'string',
      optional: false,
      customType: null as unknown as 'app_admin' | 'region_user' | 'region_maintainer' | 'region_admin',
    },
  },
  primaryKey: ['id'],
  serverName: 'role_permissions',
} as const
const routeExternalResource27CragsTable = {
  name: 'routeExternalResource27crags',
  columns: {
    id: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    regionFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'region_fk',
    },
    country_name: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    crag_id: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
    },
    description: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    externalResourcesFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'external_resources_fk',
    },
    latitude: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
    },
    location_name: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    longitude: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
    },
    name: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    path: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    searchable_id: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
    },
    searchable_type: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    url: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
  },
  primaryKey: ['id'],
  serverName: 'route_external_resource_27crags',
} as const
const routeExternalResource8ATable = {
  name: 'routeExternalResource8a',
  columns: {
    id: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    regionFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'region_fk',
    },
    areaName: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'area_name',
    },
    areaSlug: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'area_slug',
    },
    averageRating: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'average_rating',
    },
    category: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
    },
    countryName: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'country_name',
    },
    countrySlug: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'country_slug',
    },
    cragName: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'crag_name',
    },
    cragSlug: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'crag_slug',
    },
    difficulty: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    externalResourcesFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'external_resources_fk',
    },
    gradeIndex: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'grade_index',
    },
    sectorName: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'sector_name',
    },
    sectorSlug: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'sector_slug',
    },
    type: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
    },
    url: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    zlaggableId: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'zlaggable_id',
    },
    zlaggableName: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'zlaggable_name',
    },
    zlaggableSlug: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'zlaggable_slug',
    },
  },
  primaryKey: ['id'],
  serverName: 'route_external_resource_8a',
} as const
const routeExternalResourceTheCragTable = {
  name: 'routeExternalResourceTheCrag',
  columns: {
    id: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    regionFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'region_fk',
    },
    description: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    externalResourcesFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'external_resources_fk',
    },
    grade: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    name: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    node: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
    },
    rating: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
    },
    tags: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    url: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
  },
  primaryKey: ['id'],
  serverName: 'route_external_resource_the_crag',
} as const
const routeExternalResourcesTable = {
  name: 'routeExternalResources',
  columns: {
    id: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    regionFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'region_fk',
    },
    externalResource8aFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'external_resource_8a_fk',
    },
    externalResource27cragsFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'external_resource_27crags_fk',
    },
    externalResourceTheCragFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'external_resource_the_crag_fk',
    },
    routeFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'route_fk',
    },
  },
  primaryKey: ['id'],
  serverName: 'route_external_resources',
} as const
const routesTable = {
  name: 'routes',
  columns: {
    createdAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'created_at',
    },
    id: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    createdBy: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'created_by',
    },
    name: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    regionFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'region_fk',
    },
    deletedAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'deleted_at',
    },
    areaFks: {
      type: 'json',
      optional: true,
      customType: null as unknown as number[],
      serverName: 'area_fks',
    },
    areaIds: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'area_ids',
    },
    blockFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'block_fk',
    },
    description: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    externalResourcesFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'external_resources_fk',
    },
    firstAscentYear: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'first_ascent_year',
    },
    gradeFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'grade_fk',
    },
    rating: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
    },
    userGradeFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'user_grade_fk',
    },
    userRating: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'user_rating',
    },
  },
  primaryKey: ['id'],
} as const
const routesToFirstAscensionistsTable = {
  name: 'routesToFirstAscensionists',
  columns: {
    id: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    regionFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'region_fk',
    },
    firstAscensionistFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'first_ascensionist_fk',
    },
    routeFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'route_fk',
    },
  },
  primaryKey: ['id'],
  serverName: 'routes_to_first_ascensionists',
} as const
const routesToTagsTable = {
  name: 'routesToTags',
  columns: {
    regionFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'region_fk',
    },
    routeFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'route_fk',
    },
    tagFk: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'tag_fk',
    },
  },
  primaryKey: ['routeFk', 'tagFk'],
  serverName: 'routes_to_tags',
} as const
const topoRoutesTable = {
  name: 'topoRoutes',
  columns: {
    id: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    regionFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'region_fk',
    },
    path: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    routeFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'route_fk',
    },
    topoFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'topo_fk',
    },
    topType: {
      type: 'string',
      optional: false,
      customType: null as unknown as 'top' | 'topout',
      serverName: 'top_type',
    },
  },
  primaryKey: ['id'],
  serverName: 'topo_routes',
} as const
const toposTable = {
  name: 'topos',
  columns: {
    id: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    regionFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'region_fk',
    },
    blockFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'block_fk',
    },
    fileFk: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'file_fk',
    },
    order: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
    },
  },
  primaryKey: ['id'],
} as const
const userRolesTable = {
  name: 'userRoles',
  columns: {
    authUserFk: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'auth_user_fk',
    },
    id: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    role: {
      type: 'string',
      optional: false,
      customType: null as unknown as 'app_admin' | 'region_user' | 'region_maintainer' | 'region_admin',
    },
  },
  primaryKey: ['id'],
  serverName: 'user_roles',
} as const
const userSettingsTable = {
  name: 'userSettings',
  columns: {
    authUserFk: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'auth_user_fk',
    },
    contactLocale: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'contact_locale',
    },
    cookie8a: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'cookie_8a',
    },
    cookie27crags: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'cookie_27crags',
    },
    cookieTheCrag: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'cookie_the_crag',
    },
    gradingScale: {
      type: 'string',
      optional: true,
      customType: null as unknown as 'FB' | 'V',
      serverName: 'grading_scale',
    },
    id: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    notifyAscents: {
      type: 'boolean',
      optional: true,
      customType: null as unknown as boolean,
      serverName: 'notify_ascents',
    },
    notifyComments: {
      type: 'boolean',
      optional: true,
      customType: null as unknown as boolean,
      serverName: 'notify_comments',
    },
    notifyCommunity: {
      type: 'boolean',
      optional: true,
      customType: null as unknown as boolean,
      serverName: 'notify_community',
    },
    notifyDirected: {
      type: 'boolean',
      optional: true,
      customType: null as unknown as boolean,
      serverName: 'notify_directed',
    },
    notifyGuidebookEdits: {
      type: 'boolean',
      optional: true,
      customType: null as unknown as boolean,
      serverName: 'notify_guidebook_edits',
    },
    notifyReactions: {
      type: 'boolean',
      optional: true,
      customType: null as unknown as boolean,
      serverName: 'notify_reactions',
    },
    pushedUpToEventAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'pushed_up_to_event_at',
    },
    seenUpToEventAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'seen_up_to_event_at',
    },
    unitSystem: {
      type: 'string',
      optional: true,
      customType: null as unknown as 'metric' | 'imperial',
      serverName: 'unit_system',
    },
    userFk: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'user_fk',
    },
  },
  primaryKey: ['id'],
  serverName: 'user_settings',
} as const
const usersTable = {
  name: 'users',
  columns: {
    createdAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'created_at',
    },
    id: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
    authUserFk: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'auth_user_fk',
    },
    firstAscensionistFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'first_ascentionist_fk',
    },
    username: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    userSettingsFk: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'user_settings_fk',
    },
  },
  primaryKey: ['id'],
} as const
const activitiesRelationships = {
  region: [{ sourceField: ['regionFk'], destField: ['id'], destSchema: 'regions', cardinality: 'one' }],
  user: [{ sourceField: ['userFk'], destField: ['id'], destSchema: 'users', cardinality: 'one' }],
} as const
const areasRelationships = {
  areas: [{ sourceField: ['id'], destField: ['parentFk'], destSchema: 'areas', cardinality: 'many' }],
  author: [{ sourceField: ['createdBy'], destField: ['id'], destSchema: 'users', cardinality: 'one' }],
  blocks: [{ sourceField: ['id'], destField: ['areaFk'], destSchema: 'blocks', cardinality: 'many' }],
  files: [{ sourceField: ['id'], destField: ['areaFk'], destSchema: 'files', cardinality: 'many' }],
  parent: [{ sourceField: ['parentFk'], destField: ['id'], destSchema: 'areas', cardinality: 'one' }],
  parkingLocations: [{ sourceField: ['id'], destField: ['areaFk'], destSchema: 'geolocations', cardinality: 'many' }],
  region: [{ sourceField: ['regionFk'], destField: ['id'], destSchema: 'regions', cardinality: 'one' }],
} as const
const ascentsRelationships = {
  author: [{ sourceField: ['createdBy'], destField: ['id'], destSchema: 'users', cardinality: 'one' }],
  files: [{ sourceField: ['id'], destField: ['ascentFk'], destSchema: 'files', cardinality: 'many' }],
  grade: [{ sourceField: ['gradeFk'], destField: ['id'], destSchema: 'grades', cardinality: 'one' }],
  region: [{ sourceField: ['regionFk'], destField: ['id'], destSchema: 'regions', cardinality: 'one' }],
  route: [{ sourceField: ['routeFk'], destField: ['id'], destSchema: 'routes', cardinality: 'one' }],
} as const
const blocksRelationships = {
  area: [{ sourceField: ['areaFk'], destField: ['id'], destSchema: 'areas', cardinality: 'one' }],
  author: [{ sourceField: ['createdBy'], destField: ['id'], destSchema: 'users', cardinality: 'one' }],
  files: [{ sourceField: ['id'], destField: ['blockFk'], destSchema: 'files', cardinality: 'many' }],
  geolocation: [{ sourceField: ['geolocationFk'], destField: ['id'], destSchema: 'geolocations', cardinality: 'one' }],
  region: [{ sourceField: ['regionFk'], destField: ['id'], destSchema: 'regions', cardinality: 'one' }],
  routes: [{ sourceField: ['id'], destField: ['blockFk'], destSchema: 'routes', cardinality: 'many' }],
  topos: [{ sourceField: ['id'], destField: ['blockFk'], destSchema: 'topos', cardinality: 'many' }],
} as const
const bunnyStreamsRelationships = {
  file: [{ sourceField: ['fileFk'], destField: ['id'], destSchema: 'files', cardinality: 'one' }],
  region: [{ sourceField: ['regionFk'], destField: ['id'], destSchema: 'regions', cardinality: 'one' }],
} as const
const changesRelationships = {
  area: [{ sourceField: ['areaFk'], destField: ['id'], destSchema: 'areas', cardinality: 'one' }],
  ascent: [{ sourceField: ['ascentFk'], destField: ['id'], destSchema: 'ascents', cardinality: 'one' }],
  block: [{ sourceField: ['blockFk'], destField: ['id'], destSchema: 'blocks', cardinality: 'one' }],
  event: [{ sourceField: ['eventFk'], destField: ['id'], destSchema: 'events', cardinality: 'one' }],
  file: [{ sourceField: ['fileFk'], destField: ['id'], destSchema: 'files', cardinality: 'one' }],
  region: [{ sourceField: ['regionFk'], destField: ['id'], destSchema: 'regions', cardinality: 'one' }],
  route: [{ sourceField: ['routeFk'], destField: ['id'], destSchema: 'routes', cardinality: 'one' }],
  subject: [{ sourceField: ['subjectFk'], destField: ['id'], destSchema: 'users', cardinality: 'one' }],
} as const
const eventsRelationships = {
  actor: [{ sourceField: ['actorFk'], destField: ['id'], destSchema: 'users', cardinality: 'one' }],
  area: [{ sourceField: ['areaFk'], destField: ['id'], destSchema: 'areas', cardinality: 'one' }],
  ascent: [{ sourceField: ['ascentFk'], destField: ['id'], destSchema: 'ascents', cardinality: 'one' }],
  block: [{ sourceField: ['blockFk'], destField: ['id'], destSchema: 'blocks', cardinality: 'one' }],
  changes: [{ sourceField: ['id'], destField: ['eventFk'], destSchema: 'changes', cardinality: 'many' }],
  file: [{ sourceField: ['fileFk'], destField: ['id'], destSchema: 'files', cardinality: 'one' }],
  reactions: [{ sourceField: ['id'], destField: ['eventFk'], destSchema: 'reactions', cardinality: 'many' }],
  region: [{ sourceField: ['regionFk'], destField: ['id'], destSchema: 'regions', cardinality: 'one' }],
  route: [{ sourceField: ['routeFk'], destField: ['id'], destSchema: 'routes', cardinality: 'one' }],
  subject: [{ sourceField: ['subjectFk'], destField: ['id'], destSchema: 'users', cardinality: 'one' }],
} as const
const favoritesRelationships = {
  area: [{ sourceField: ['areaFk'], destField: ['id'], destSchema: 'areas', cardinality: 'one' }],
  authUser: [{ sourceField: ['authUserFk'], destField: ['id'], destSchema: 'users', cardinality: 'one' }],
  block: [{ sourceField: ['blockFk'], destField: ['id'], destSchema: 'blocks', cardinality: 'one' }],
  region: [{ sourceField: ['regionFk'], destField: ['id'], destSchema: 'regions', cardinality: 'one' }],
  route: [{ sourceField: ['routeFk'], destField: ['id'], destSchema: 'routes', cardinality: 'one' }],
  user: [{ sourceField: ['userFk'], destField: ['id'], destSchema: 'users', cardinality: 'one' }],
} as const
const filesRelationships = {
  area: [{ sourceField: ['areaFk'], destField: ['id'], destSchema: 'areas', cardinality: 'one' }],
  ascent: [{ sourceField: ['ascentFk'], destField: ['id'], destSchema: 'ascents', cardinality: 'one' }],
  author: [{ sourceField: ['createdBy'], destField: ['id'], destSchema: 'users', cardinality: 'one' }],
  block: [{ sourceField: ['blockFk'], destField: ['id'], destSchema: 'blocks', cardinality: 'one' }],
  bunnyStream: [{ sourceField: ['bunnyStreamFk'], destField: ['id'], destSchema: 'bunnyStreams', cardinality: 'one' }],
  region: [{ sourceField: ['regionFk'], destField: ['id'], destSchema: 'regions', cardinality: 'one' }],
  route: [{ sourceField: ['routeFk'], destField: ['id'], destSchema: 'routes', cardinality: 'one' }],
} as const
const firstAscensionistsRelationships = {
  region: [{ sourceField: ['regionFk'], destField: ['id'], destSchema: 'regions', cardinality: 'one' }],
  routes: [
    {
      sourceField: ['id'],
      destField: ['firstAscensionistFk'],
      destSchema: 'routesToFirstAscensionists',
      cardinality: 'many',
    },
  ],
  user: [{ sourceField: ['userFk'], destField: ['id'], destSchema: 'users', cardinality: 'one' }],
} as const
const geolocationsRelationships = {
  area: [{ sourceField: ['areaFk'], destField: ['id'], destSchema: 'areas', cardinality: 'one' }],
  block: [{ sourceField: ['blockFk'], destField: ['id'], destSchema: 'blocks', cardinality: 'one' }],
  region: [{ sourceField: ['regionFk'], destField: ['id'], destSchema: 'regions', cardinality: 'one' }],
} as const
const gradesRelationships = {
  ascents: [{ sourceField: ['id'], destField: ['gradeFk'], destSchema: 'ascents', cardinality: 'many' }],
  routes: [{ sourceField: ['id'], destField: ['gradeFk'], destSchema: 'routes', cardinality: 'many' }],
} as const
const notificationsRelationships = {
  actor: [{ sourceField: ['actorFk'], destField: ['id'], destSchema: 'users', cardinality: 'one' }],
  area: [{ sourceField: ['areaFk'], destField: ['id'], destSchema: 'areas', cardinality: 'one' }],
  ascent: [{ sourceField: ['ascentFk'], destField: ['id'], destSchema: 'ascents', cardinality: 'one' }],
  authUser: [{ sourceField: ['authUserFk'], destField: ['id'], destSchema: 'users', cardinality: 'one' }],
  block: [{ sourceField: ['blockFk'], destField: ['id'], destSchema: 'blocks', cardinality: 'one' }],
  event: [{ sourceField: ['eventFk'], destField: ['id'], destSchema: 'events', cardinality: 'one' }],
  file: [{ sourceField: ['fileFk'], destField: ['id'], destSchema: 'files', cardinality: 'one' }],
  reaction: [{ sourceField: ['reactionFk'], destField: ['id'], destSchema: 'reactions', cardinality: 'one' }],
  region: [{ sourceField: ['regionFk'], destField: ['id'], destSchema: 'regions', cardinality: 'one' }],
  route: [{ sourceField: ['routeFk'], destField: ['id'], destSchema: 'routes', cardinality: 'one' }],
  subject: [{ sourceField: ['subjectFk'], destField: ['id'], destSchema: 'users', cardinality: 'one' }],
  user: [{ sourceField: ['userFk'], destField: ['id'], destSchema: 'users', cardinality: 'one' }],
} as const
const pushSubscriptionsRelationships = {
  authUser: [{ sourceField: ['authUserFk'], destField: ['id'], destSchema: 'users', cardinality: 'one' }],
  user: [{ sourceField: ['userFk'], destField: ['id'], destSchema: 'users', cardinality: 'one' }],
} as const
const reactionsRelationships = {
  children: [{ sourceField: ['id'], destField: ['parentFk'], destSchema: 'reactions', cardinality: 'many' }],
  event: [{ sourceField: ['eventFk'], destField: ['id'], destSchema: 'events', cardinality: 'one' }],
  parent: [{ sourceField: ['parentFk'], destField: ['id'], destSchema: 'reactions', cardinality: 'one' }],
  region: [{ sourceField: ['regionFk'], destField: ['id'], destSchema: 'regions', cardinality: 'one' }],
  user: [{ sourceField: ['userFk'], destField: ['id'], destSchema: 'users', cardinality: 'one' }],
} as const
const regionInvitationsRelationships = {
  acceptedBy: [{ sourceField: ['acceptedByFk'], destField: ['id'], destSchema: 'users', cardinality: 'one' }],
  invitedBy: [{ sourceField: ['invitedByFk'], destField: ['id'], destSchema: 'users', cardinality: 'one' }],
  region: [{ sourceField: ['regionFk'], destField: ['id'], destSchema: 'regions', cardinality: 'one' }],
} as const
const regionMembersRelationships = {
  authUser: [{ sourceField: ['authUserFk'], destField: ['id'], destSchema: 'users', cardinality: 'one' }],
  invitedBy: [{ sourceField: ['invitedByFk'], destField: ['id'], destSchema: 'users', cardinality: 'one' }],
  region: [{ sourceField: ['regionFk'], destField: ['id'], destSchema: 'regions', cardinality: 'one' }],
  rolePermission: [{ sourceField: ['role'], destField: ['role'], destSchema: 'rolePermissions', cardinality: 'one' }],
  user: [{ sourceField: ['userFk'], destField: ['id'], destSchema: 'users', cardinality: 'one' }],
} as const
const regionsRelationships = {
  author: [{ sourceField: ['createdBy'], destField: ['id'], destSchema: 'users', cardinality: 'one' }],
  members: [{ sourceField: ['id'], destField: ['regionFk'], destSchema: 'regionMembers', cardinality: 'many' }],
} as const
const rolePermissionsRelationships = {
  regionMembers: [{ sourceField: ['role'], destField: ['role'], destSchema: 'regionMembers', cardinality: 'many' }],
} as const
const routeExternalResource27CragsRelationships = {
  externalResources: [
    {
      sourceField: ['externalResourcesFk'],
      destField: ['id'],
      destSchema: 'routeExternalResources',
      cardinality: 'one',
    },
  ],
  region: [{ sourceField: ['regionFk'], destField: ['id'], destSchema: 'regions', cardinality: 'one' }],
} as const
const routeExternalResource8ARelationships = {
  externalResources: [
    {
      sourceField: ['externalResourcesFk'],
      destField: ['id'],
      destSchema: 'routeExternalResources',
      cardinality: 'one',
    },
  ],
  region: [{ sourceField: ['regionFk'], destField: ['id'], destSchema: 'regions', cardinality: 'one' }],
} as const
const routeExternalResourceTheCragRelationships = {
  externalResources: [
    {
      sourceField: ['externalResourcesFk'],
      destField: ['id'],
      destSchema: 'routeExternalResources',
      cardinality: 'one',
    },
  ],
  region: [{ sourceField: ['regionFk'], destField: ['id'], destSchema: 'regions', cardinality: 'one' }],
} as const
const routeExternalResourcesRelationships = {
  externalResource8a: [
    {
      sourceField: ['externalResource8aFk'],
      destField: ['id'],
      destSchema: 'routeExternalResource8a',
      cardinality: 'one',
    },
  ],
  externalResource27crags: [
    {
      sourceField: ['externalResource27cragsFk'],
      destField: ['id'],
      destSchema: 'routeExternalResource27crags',
      cardinality: 'one',
    },
  ],
  externalResourceTheCrag: [
    {
      sourceField: ['externalResourceTheCragFk'],
      destField: ['id'],
      destSchema: 'routeExternalResourceTheCrag',
      cardinality: 'one',
    },
  ],
  region: [{ sourceField: ['regionFk'], destField: ['id'], destSchema: 'regions', cardinality: 'one' }],
  route: [{ sourceField: ['routeFk'], destField: ['id'], destSchema: 'routes', cardinality: 'one' }],
} as const
const routesRelationships = {
  ascents: [{ sourceField: ['id'], destField: ['routeFk'], destSchema: 'ascents', cardinality: 'many' }],
  author: [{ sourceField: ['createdBy'], destField: ['id'], destSchema: 'users', cardinality: 'one' }],
  block: [{ sourceField: ['blockFk'], destField: ['id'], destSchema: 'blocks', cardinality: 'one' }],
  externalResources: [
    {
      sourceField: ['externalResourcesFk'],
      destField: ['id'],
      destSchema: 'routeExternalResources',
      cardinality: 'one',
    },
  ],
  files: [{ sourceField: ['id'], destField: ['routeFk'], destSchema: 'files', cardinality: 'many' }],
  firstAscents: [
    { sourceField: ['id'], destField: ['routeFk'], destSchema: 'routesToFirstAscensionists', cardinality: 'many' },
  ],
  grade: [{ sourceField: ['gradeFk'], destField: ['id'], destSchema: 'grades', cardinality: 'one' }],
  region: [{ sourceField: ['regionFk'], destField: ['id'], destSchema: 'regions', cardinality: 'one' }],
  tags: [{ sourceField: ['id'], destField: ['routeFk'], destSchema: 'routesToTags', cardinality: 'many' }],
  topoRoutes: [{ sourceField: ['id'], destField: ['routeFk'], destSchema: 'topoRoutes', cardinality: 'many' }],
} as const
const routesToFirstAscensionistsRelationships = {
  firstAscensionist: [
    { sourceField: ['firstAscensionistFk'], destField: ['id'], destSchema: 'firstAscensionists', cardinality: 'one' },
  ],
  region: [{ sourceField: ['regionFk'], destField: ['id'], destSchema: 'regions', cardinality: 'one' }],
  route: [{ sourceField: ['routeFk'], destField: ['id'], destSchema: 'routes', cardinality: 'one' }],
} as const
const routesToTagsRelationships = {
  region: [{ sourceField: ['regionFk'], destField: ['id'], destSchema: 'regions', cardinality: 'one' }],
  route: [{ sourceField: ['routeFk'], destField: ['id'], destSchema: 'routes', cardinality: 'one' }],
} as const
const topoRoutesRelationships = {
  region: [{ sourceField: ['regionFk'], destField: ['id'], destSchema: 'regions', cardinality: 'one' }],
  route: [{ sourceField: ['routeFk'], destField: ['id'], destSchema: 'routes', cardinality: 'one' }],
  topo: [{ sourceField: ['topoFk'], destField: ['id'], destSchema: 'topos', cardinality: 'one' }],
} as const
const toposRelationships = {
  block: [{ sourceField: ['blockFk'], destField: ['id'], destSchema: 'blocks', cardinality: 'one' }],
  file: [{ sourceField: ['fileFk'], destField: ['id'], destSchema: 'files', cardinality: 'one' }],
  region: [{ sourceField: ['regionFk'], destField: ['id'], destSchema: 'regions', cardinality: 'one' }],
  routes: [{ sourceField: ['id'], destField: ['topoFk'], destSchema: 'topoRoutes', cardinality: 'many' }],
} as const
const userRolesRelationships = {
  rolePermission: [{ sourceField: ['role'], destField: ['role'], destSchema: 'rolePermissions', cardinality: 'one' }],
} as const
const userSettingsRelationships = {
  authUser: [{ sourceField: ['authUserFk'], destField: ['id'], destSchema: 'users', cardinality: 'one' }],
  user: [{ sourceField: ['userFk'], destField: ['id'], destSchema: 'users', cardinality: 'one' }],
} as const
const usersRelationships = {
  areas: [{ sourceField: ['id'], destField: ['createdBy'], destSchema: 'areas', cardinality: 'many' }],
  ascents: [{ sourceField: ['id'], destField: ['createdBy'], destSchema: 'ascents', cardinality: 'many' }],
  authUser: [{ sourceField: ['authUserFk'], destField: ['id'], destSchema: 'users', cardinality: 'one' }],
  blocks: [{ sourceField: ['id'], destField: ['createdBy'], destSchema: 'blocks', cardinality: 'many' }],
  favorites: [{ sourceField: ['id'], destField: ['userFk'], destSchema: 'favorites', cardinality: 'many' }],
  firstAscensionist: [
    { sourceField: ['firstAscensionistFk'], destField: ['id'], destSchema: 'firstAscensionists', cardinality: 'one' },
  ],
  pushSubscriptions: [
    { sourceField: ['id'], destField: ['userFk'], destSchema: 'pushSubscriptions', cardinality: 'many' },
  ],
  regionMemberships: [{ sourceField: ['id'], destField: ['userFk'], destSchema: 'regionMembers', cardinality: 'many' }],
  routes: [{ sourceField: ['id'], destField: ['createdBy'], destSchema: 'routes', cardinality: 'many' }],
  userSettings: [
    { sourceField: ['userSettingsFk'], destField: ['id'], destSchema: 'userSettings', cardinality: 'one' },
  ],
} as const
/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  tables: {
    activities: activitiesTable,
    areas: areasTable,
    ascents: ascentsTable,
    blocks: blocksTable,
    bunnyStreams: bunnyStreamsTable,
    changes: changesTable,
    clientErrorLogs: clientErrorLogsTable,
    events: eventsTable,
    favorites: favoritesTable,
    files: filesTable,
    firstAscensionists: firstAscensionistsTable,
    geolocations: geolocationsTable,
    grades: gradesTable,
    notifications: notificationsTable,
    pushSubscriptions: pushSubscriptionsTable,
    reactions: reactionsTable,
    regionInvitations: regionInvitationsTable,
    regionMembers: regionMembersTable,
    regions: regionsTable,
    rolePermissions: rolePermissionsTable,
    routeExternalResource27crags: routeExternalResource27CragsTable,
    routeExternalResource8a: routeExternalResource8ATable,
    routeExternalResourceTheCrag: routeExternalResourceTheCragTable,
    routeExternalResources: routeExternalResourcesTable,
    routes: routesTable,
    routesToFirstAscensionists: routesToFirstAscensionistsTable,
    routesToTags: routesToTagsTable,
    topoRoutes: topoRoutesTable,
    topos: toposTable,
    userRoles: userRolesTable,
    userSettings: userSettingsTable,
    users: usersTable,
  },
  relationships: {
    activities: activitiesRelationships,
    areas: areasRelationships,
    ascents: ascentsRelationships,
    blocks: blocksRelationships,
    bunnyStreams: bunnyStreamsRelationships,
    changes: changesRelationships,
    events: eventsRelationships,
    favorites: favoritesRelationships,
    files: filesRelationships,
    firstAscensionists: firstAscensionistsRelationships,
    geolocations: geolocationsRelationships,
    grades: gradesRelationships,
    notifications: notificationsRelationships,
    pushSubscriptions: pushSubscriptionsRelationships,
    reactions: reactionsRelationships,
    regionInvitations: regionInvitationsRelationships,
    regionMembers: regionMembersRelationships,
    regions: regionsRelationships,
    rolePermissions: rolePermissionsRelationships,
    routeExternalResource27crags: routeExternalResource27CragsRelationships,
    routeExternalResource8a: routeExternalResource8ARelationships,
    routeExternalResourceTheCrag: routeExternalResourceTheCragRelationships,
    routeExternalResources: routeExternalResourcesRelationships,
    routes: routesRelationships,
    routesToFirstAscensionists: routesToFirstAscensionistsRelationships,
    routesToTags: routesToTagsRelationships,
    topoRoutes: topoRoutesRelationships,
    topos: toposRelationships,
    userRoles: userRolesRelationships,
    userSettings: userSettingsRelationships,
    users: usersRelationships,
  },
  enableLegacyQueries: false,
  enableLegacyMutators: false,
} as const

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema
/**
 * Represents a row from the "activities" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Activity = Row<(typeof schema)['tables']['activities']>
/**
 * Represents a row from the "areas" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Area = Row<(typeof schema)['tables']['areas']>
/**
 * Represents a row from the "ascents" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Ascent = Row<(typeof schema)['tables']['ascents']>
/**
 * Represents a row from the "blocks" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Block = Row<(typeof schema)['tables']['blocks']>
/**
 * Represents a row from the "bunnyStreams" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type BunnyStream = Row<(typeof schema)['tables']['bunnyStreams']>
/**
 * Represents a row from the "changes" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Change = Row<(typeof schema)['tables']['changes']>
/**
 * Represents a row from the "clientErrorLogs" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ClientErrorLog = Row<(typeof schema)['tables']['clientErrorLogs']>
/**
 * Represents a row from the "events" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Event = Row<(typeof schema)['tables']['events']>
/**
 * Represents a row from the "favorites" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Favorite = Row<(typeof schema)['tables']['favorites']>
/**
 * Represents a row from the "files" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type File = Row<(typeof schema)['tables']['files']>
/**
 * Represents a row from the "firstAscensionists" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type FirstAscensionist = Row<(typeof schema)['tables']['firstAscensionists']>
/**
 * Represents a row from the "geolocations" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Geolocation = Row<(typeof schema)['tables']['geolocations']>
/**
 * Represents a row from the "grades" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Grade = Row<(typeof schema)['tables']['grades']>
/**
 * Represents a row from the "notifications" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Notification = Row<(typeof schema)['tables']['notifications']>
/**
 * Represents a row from the "pushSubscriptions" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type PushSubscription = Row<(typeof schema)['tables']['pushSubscriptions']>
/**
 * Represents a row from the "reactions" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Reaction = Row<(typeof schema)['tables']['reactions']>
/**
 * Represents a row from the "regionInvitations" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type RegionInvitation = Row<(typeof schema)['tables']['regionInvitations']>
/**
 * Represents a row from the "regionMembers" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type RegionMember = Row<(typeof schema)['tables']['regionMembers']>
/**
 * Represents a row from the "regions" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Region = Row<(typeof schema)['tables']['regions']>
/**
 * Represents a row from the "rolePermissions" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type RolePermission = Row<(typeof schema)['tables']['rolePermissions']>
/**
 * Represents a row from the "routeExternalResource27crags" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type RouteExternalResource27Crag = Row<(typeof schema)['tables']['routeExternalResource27crags']>
/**
 * Represents a row from the "routeExternalResource8a" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type RouteExternalResource8A = Row<(typeof schema)['tables']['routeExternalResource8a']>
/**
 * Represents a row from the "routeExternalResourceTheCrag" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type RouteExternalResourceTheCrag = Row<(typeof schema)['tables']['routeExternalResourceTheCrag']>
/**
 * Represents a row from the "routeExternalResources" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type RouteExternalResource = Row<(typeof schema)['tables']['routeExternalResources']>
/**
 * Represents a row from the "routes" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Route = Row<(typeof schema)['tables']['routes']>
/**
 * Represents a row from the "routesToFirstAscensionists" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type RoutesToFirstAscensionist = Row<(typeof schema)['tables']['routesToFirstAscensionists']>
/**
 * Represents a row from the "routesToTags" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type RoutesToTag = Row<(typeof schema)['tables']['routesToTags']>
/**
 * Represents a row from the "topoRoutes" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type TopoRoute = Row<(typeof schema)['tables']['topoRoutes']>
/**
 * Represents a row from the "topos" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Topo = Row<(typeof schema)['tables']['topos']>
/**
 * Represents a row from the "userRoles" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type UserRole = Row<(typeof schema)['tables']['userRoles']>
/**
 * Represents a row from the "userSettings" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type UserSetting = Row<(typeof schema)['tables']['userSettings']>
/**
 * Represents a row from the "users" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type User = Row<(typeof schema)['tables']['users']>

/**
 * Represents the ZQL query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const zql = createBuilder(schema)
/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const builder = zql

/** Defines the default types for Zero */
declare module '@rocicorp/zero' {
  interface DefaultTypes {
    schema: Schema
  }
}
